### PR TITLE
[DNM] Update SDK version to goz-phase-2

### PR DESCRIPTION
**Pull request by jackzampolin**

### CODE REVIEW

**Review by alessio — APPROVED** [review]
Please run `go mod tidy`. Looks good otherwise

**Comment by jackzampolin** [comment]
This is a do not merge PR, so lets not merge this?

**Comment by tac0turtle** [comment]
what is the reasoning for keeping a DNM merge around if there is a tag for it?

**Review by alessio — CHANGES_REQUESTED** [review]
IMHO the tag is superfluos and a branch like this is definitely easier to handle. Hence blocking this to prevent this branch from being merged before phase 2 is over.

EDIT: @marbar3778 'cause It's easier to just commit fixes here whilst tags need to be overwritten

**Comment by tac0turtle** [comment]
closing this PR as GoZ has ended.

**Pull request closed without merging**
