### PR TITLE
v5.0.9

### PR DESCRIPTION
**Pull request by faddat**
## v5.0.9

This pull request updates gaia v5 to the latest applicable cosmos-sdk, tendermint, and tm-db library versions.

#1449 
______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/main/README.md#merging-a-pr))

### CODE REVIEW

**Comment by okwme** [comment]
Thanks for the PR @faddat , can you check the errors in CI?

**Comment by faddat** [comment]
These errors are caused by CI itself

Sorry, separation of concerns...

https://github.com/cosmos/gaia/runs/6036385688?check_suite_focus=true

Is a CI issue.  CI caches so much that it cannot go backwards well.

**Comment by faddat** [comment]
Root.go was just root.go being root.go ;)

I could fix the linter but it would change CI some.

#1449

**Comment by faddat** [comment]
fixing linter....

Billy, the errors in CI, aren't related to this PR.  They're caused by how the hub team had golangci-lint configured and I reported that long ago.

#1449

**Comment by okwme** [comment]
opened up an issue to resolve stable release policy  #1549 
it's just a draft and i suggested only supporting only one version behind the current live network.
that would mean that v5 vega should only have security bug-fixes but cosmos sdk [v0.42.11](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.42.11) and tendermint [v34.16 ](https://github.com/tendermint/tendermint/blob/v0.34.16/CHANGELOG.md#v0.34.16) both contain bug fixes.

**Pull request merged**
