### PR TITLE
Docs update

### PR DESCRIPTION
**Pull request by lovincyrus**
## Description

1.0.169 changes: https://github.com/cosmos/vuepress-theme-cosmos/pull/84
- newsletter signup form: zoho → mailerlite
- top banner (Stargate): https://github.com/cosmos/vuepress-theme-cosmos/pull/82#issue-455323605
   - banner content will be updated via https://github.com/cosmos/cosmos.network/pull/47

image

## Related:
- https://github.com/cosmos/gaia/issues/446

---

- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/develop/CONTRIBUTING.md#pr-targeting))

- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote tests
- [ ] Updated relevant documentation (`docs/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Reviewed `Files changed` in the github PR explorer

### CODE REVIEW

**Review by tac0turtle — APPROVED** [review]
gonna push this through because i havent migrated docs from master to main but we dont use master in this repo anymore.

**Comment by tac0turtle** [comment]
@alessio @okwme im not sure who has perms for this repo but can you remove required for master. Its not used as the default branch anymore but docs havent been migrated over yet.

**Comment by okwme** [comment]
@marbar3778 updated

**Comment by tac0turtle** [comment]
thank you !!

**Pull request merged**
