### PR TITLE
bug(app config): fix the wrong `bypass-min-fee-msg-types` key parse from the app config file

### LINKED ISSUE #1486: Config app.toml param bypass-min-fee-msg-types not work
## Summary of Bug
Append parameter `bypass-min-fee-msg-types` to `app.toml` not work

This can be work if `bypass-min-fee-msg-types` is placed at the beginning of `app.toml` or before [Telemetry]

## Version

main-97a79c38beab15032347344b2d588a59ff2b292a
## Steps to Reproduce

1. gaiad testnet --v 1
2. update app.toml  `bypass-min-fee-msg-types` params to ['/cosmos.staking.v1beta1.MsgDelegate']
3. gaiad start --home ./mytestnet/node0/gaiad
5. gaiad tx staking delegate cosmosvaloper105jmphl0qh04ner2v2dxkdvwhcgkvar4jyjn7h 1stake --from node0 --chain-id=chain-AW5wPV

result:
```
{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgDelegate","delegator_address":"cosmos1l7dvcejsa2tswqrzwr0rjmqcwmjxgwalztt6js","validator_address":"cosmosvaloper105jmphl0qh04ner2v2dxkdvwhcgkvar4jyjn7h","amount":{"denom":"stake","amount":"1"}}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]}

confirm transaction before signing and broadcasting [y/N]: y
code: 13
codespace: sdk
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: 'insufficient fees; got:  required: 20stake: insufficient fee'
timestamp: ""
tx: null
txhash: 1703C4958EE89149795D7F3666411ACF0D03409500DF0FC17552860090F67EA8
```
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

### PR DESCRIPTION
**Pull request by Pantani**
close #1486

## Description

The current `bypass-min-fee-msg-types` parameter is not parsing correctly from the `app.toml` config file. The chain is only using the default values.

## Solution

This PR fix the right variable path to use `state-sync.bypass-min-fee-msg-types` Instead from `bypass-min-fee-msg-types` only.

### CODE REVIEW

**Comment by yaruwangway** [comment]
Hi the `bypass-min-fee-msg-types` is parsed from app.toml if the `bypass-min-fee-msg-types` at the either the beginning or end of app.toml. 

we want `bypass-min-fee-msg-types` can be parse when put `bypass-min-fee-msg-types` at any place of the app.toml. does this pr solve this issue ?

**Comment by Pantani** [comment]
> Hi the `bypass-min-fee-msg-types` is parsed from app.toml if the `bypass-min-fee-msg-types` at the either the beginning or end of app.toml.
> 
> we want `bypass-min-fee-msg-types` can be parse when put `bypass-min-fee-msg-types` at any place of the app.toml. does this pr solve this issue ?

We can't add the key add the end of the file because the key will be added in the last table level (`state-sync`). For we can keep them at the top level of the file, we should add them before the first TOML table (`telemetry`):

https://github.com/toml-lang/toml/issues/394
https://github.com/toml-lang/toml/issues/565

I fixed the PR to add the custom Gaia configs in the second line of the file. WDYT?

E.G.:
```toml
# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

###############################################################################
###                        Custom Gaia Configuration                        ###
###############################################################################
# bypass-min-fee-msg-types defines custom message types the operator may set that
# will bypass minimum fee checks during CheckTx.
#
# Example:
# ["/ibc.core.channel.v1.MsgRecvPacket", "/ibc.core.channel.v1.MsgAcknowledgement", ...]
bypass-min-fee-msg-types = ["/ibc.core.channel.v1.MsgRecvPacket", "/ibc.core.channel.v1.MsgAcknowledgement", "/ibc.core.client.v1.MsgUpdateClient", ]

###############################################################################
###                           Base Configuration                            ###
###############################################################################

# The minimum gas prices a validator is willing to accept for processing a
# transaction. A transaction's fees must meet the minimum of any denomination
# specified in this config (e.g. 0.25token1;0.0001token2).
minimum-gas-prices = "0.025uatom"
```

**Comment by yaruwangway** [comment]
LGTM. 👍
then we need a doc somewhere to tell users using old app.toml to insert the `bypass-min-fee-msg-types` at the beginning of the file.

**Review by yaruwangway — APPROVED** [review]

**Comment by faddat** [comment]
thank you.  We were having the same issue with eve.

**Review by okwme — APPROVED** [review]

**Comment by okwme** [comment]
@Pantani feel free to merge while the broken link issue is resolved in parallel

**Pull request merged**
