### PR TITLE
gaia v6.0.0-rc2

### LINKED ISSUE #966: support upgrade to tendermint 0.35
## Summary
support key migration when upgrade to tendermint 0.35

## Problem Definition
 In Tendermint 0.35, the format of keys in the database are changed. Operators who are running nodes that started as 0.34 will need to [migrate the key](https://github.com/tendermint/tendermint/pull/6790) formats.

## Proposal
Gaia will migrate the key format through [pre-upgrade handler](https://github.com/cosmos/cosmos-sdk/issues/10047) in cosmovisor before execute the new binary. We could use cosmovisor with a flag `--pre-upgrade-hook` to run a script to migrate the key.

TODO:
- [ ] add key migration cli
- [ ] define the pre-upgrade handler and the script to run for migration
- [ ] tests

Ref:
https://github.com/cosmos/cosmos-sdk/issues/10047
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

### LINKED ISSUE #969: Remove Legacy Migration Code
## Summary

There are two files that I believe are related to legacy migration paths/logic:

- `app/migrate.go`
- `app/pubkey_replacement.go`

These files relay on legacy SDK code that is marked deprecated and will be removed in future a release.

Not sure who the best person to ask is, but I wager we can just probably just remove these now.

/cc @yaruwangway @okwme 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

### PR DESCRIPTION
**Pull request by yaruwangway**
Closes: #969 #991

## Description
This PR is for releasing gaia v6.0.0-rc2. The following changes are included:
- [x] Change Go version to 1.17
- [x] Add IBC Router to Hub if proposal_id 56 passes the voting
- [x] [fix: testnet cli command update genesis supply](https://github.com/cosmos/gaia/pull/991)
- [x] [Remove legacy migration code](https://github.com/cosmos/gaia/issues/969#issue-997234532)
- [x] Bump ibc-go to [v1.2.1](https://github.com/cosmos/ibc-go/releases/tag/v1.2.1)

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/main/README.md#merging-a-pr))

### CODE REVIEW

**Comment by okwme** [comment]
why are all of these other replace lines necessary now?

**Comment by jaybxyz** [comment]
@yaruwangway Quick question here. Is there a plan to upgrade Cosmos SDK to [v0.44.1](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.44.1)? If so, we are going to have to bump up the SDK version in [liquidity](https://github.com/tendermint/liquidity) module and release a new version.

**Comment by yaruwangway** [comment]
> @yaruwangway Quick question here. Is there a plan to upgrade Cosmos SDK to [v0.44.1](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.44.1)? If so, we are going to have to bump up the SDK version in [liquidity](https://github.com/tendermint/liquidity) module and release a new version.

Hi @kogisin yes, we bumped to 0.44.1 (sorry for the late reply). v0.44.0 is not safe to use when performing v0.42->v0.44 in-place store upgrades in vega upgrade.

**Review by okwme — APPROVED** [review]
I'm approving on behalf of @jackzampolin :+1:

**Pull request merged**
