### PR TITLE
Bump the tendermint version to v0.34.17

### PR DESCRIPTION
**Pull request by zmanian**
The cosmos hub has been experiencing consensus instability around tally blocks for governance proposals.

Iqlusion has found https://github.com/tendermint/tendermint/issues/7992 and https://github.com/tendermint/tendermint/issues/7994 which are in Tendermint v0.34.17 reduce the p2p and consensus instability associated with blocks that take a long time to process.

I would appreciate merging this PR and doing a Gaia release.

### CODE REVIEW

**Review by alexanderbez — APPROVED** [review]

**Comment by zmanian** [comment]
This needs a cosmos-sdk release because of changes to reset on Tendermint

**Comment by alexanderbez** [comment]
> This needs a cosmos-sdk release because of changes to reset on Tendermint

for 0.45.x? I'll take care of that.

**Comment by alexanderbez** [comment]
PR to update v0.45.x of the SDK -> https://github.com/cosmos/cosmos-sdk/pull/11562

**Comment by zmanian** [comment]
I made this https://github.com/cosmos/cosmos-sdk/pull/11563

**Comment by alexanderbez** [comment]
> I made this [cosmos/cosmos-sdk#11563](https://github.com/cosmos/cosmos-sdk/pull/11563)

Looks good! Just remove the commented-out `UnsafeResetAllCmd` 👍

**Comment by alexanderbez** [comment]
~~Blocked on https://github.com/tendermint/tendermint/pull/8270~~

**Comment by alexanderbez** [comment]
The Tendermint update to v0.34.19 has been backported to SDK 0.44.x and 0.45.x. Waiting on releases of each and then we can finally wrap up and update Gaia.

**Comment by alexanderbez** [comment]
Done by https://github.com/cosmos/gaia/pull/1405

**Pull request closed without merging**
