### PR TITLE
Delete CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by faddat**
It's time to choose. You can either admit that you have absolutely no place in having a code of conduct at all, and delete the code of conduct, or you can knock out Jae+aib (thought crime: hatefulness  and/or stirring up ethnoreligious hatred) and me (thought crime: Yes I did gender the hub, and describe her as overweight because she is a relatively slow computer program).

Freedom or censorship?

O and when someone threatens me, I do call em de badsiewordsies.

### CODE REVIEW

**Comment by faddat** [comment]
Screenshot_20221112-034356

**Comment by faddat** [comment]
Screenshot_20221111-114140
Screenshot_20221110-091118
Screenshot_20221110-090352
Screenshot_20221110-090334

**Comment by faddat** [comment]
Let's talk about the realities of this code of conduct.

An unpaid contributor cannot compare the hub to a fat woman

One of the founders can do the above.

This is something to get you thinking:

**Comment by mmulji-ic** [comment]
@faddat please see the comment here https://github.com/cosmos/gaia/pull/1894

**Comment by jackzampolin** [comment]
This code of conduct serves no purpose and should be deleted.

**Review by jackzampolin — APPROVED** [review]

**Pull request merged**
