### PR TITLE
sdk v0.45.8 for gaia v7.0.x

### PR DESCRIPTION
**Pull request by faddat**
This PR upgrades gaia to use cosmos-sdk v0.45.7, which introduces a number of performance improvements originally developed at Osmosis at https://github.com/osmosis-labs/iavl

These improvements were later merged to the upstream iavl, and became iavl v0.19.*

The PR also bumps ibc-go to v3.0.2

This PR requires an upstream merge in the liquidity module.

* https://github.com/Gravity-Devs/liquidity/pull/21

I'd take this PR out of `draft`, once we've got upstream patched so that the liqudity module can be a clean import again.

This PR has been tested by running it using the snapshot from:

https://quicksync.io/networks/cosmos.html

### CODE REVIEW

**Comment by okwme** [comment]
hi @faddat thanks for this PR!
looks like the e2e test is failing, is there a breaking change to the API that isn't being accounted for in the release?
seems the error has to do with a config file, were you able to pass E2E tests locally?

**Comment by jaybxyz** [comment]
The `liquidity` module has new release [v1.5.2](https://github.com/Gravity-Devs/liquidity/releases/tag/v1.5.2) that bumped Cosmos SDK to v0.45.8.

**Comment by okwme** [comment]
@crodriguezvega is this the correct version of ibc?
ibc 3.2.1 uses cosmos sdk v0.45.8 right?

**Comment by faddat** [comment]
@okwme Yep, it is the correct version of ibc, I had mass confusion on this item, as well, here's the breakdown:

* On certain starport chains the combo of v0.45.8 and v0.34.21 can cause issues, but only with tests.
* In the case of Gaia, since we don't want a state breaking change, v3.0.2 for ibc and v0.45.8 for sdk and tendermint v0.34.21 are correct.  IBC-go v3.2.0 is a state breaking change.

**Pull request closed without merging**
