### PR TITLE
pass in binary names to version through build tags

### PR DESCRIPTION
**Pull request by rigelrozanski**
For these updates https://github.com/cosmos/cosmos-sdk/pull/4361

Not sure how to update the version of sdk that gaia is pointing at.. feel free to push here?

### CODE REVIEW

**Review by alexanderbez — APPROVED** [review]

**Comment by alessio** [comment]
Good one! Reproducible builds need update as well - I can take care of that though

**Comment by rigelrozanski** [comment]
@alessio I'll leave you the honours of merging this when your "delete gaia" PR gets merged in the sdk

**Comment by alexanderbez** [comment]
Weird. Builds/installs for me locally. Not sure why CI is failing though.

**Comment by alexanderbez** [comment]
Culprit: 

```
# Makefile

$(RUNSIM):
    go get github.com/cosmos/cosmos-sdk/contrib/runsim@v0.28.2-0.20190517070908-8ff9b25facc5
    go install github.com/cosmos/cosmos-sdk/contrib/runsim
```

@alessio will address/fix this 👍

**Review by alessio — APPROVED** [review]

**Review by alessio — CHANGES_REQUESTED** [review]
Sorry - approved without thinking enough. Reproducible builds build script needs refresh as well

**Review by alessio — APPROVED** [review]
Everything should be OK now

**Pull request merged**
