### PR TITLE
refactor: errors module

### LINKED ISSUE #1786: chore: change the deprecated `sdkerrors` package to `cosmossdk.io/errors`
## Summary

The current `github.com/cosmos/cosmos-sdk/types/errors` package was deprecated. We should use the new one `cosmossdk.io/errors`

## Type

Code Debt

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

### PR DESCRIPTION
**Pull request by faddat**
## Description

This PR makes gaia use the errors module from sdk 47+.  That will ease the transition to 47.

Closes https://github.com/cosmos/gaia/issues/1786

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [ ] Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] Added `!` to the type prefix if API or client breaking change
* [ ] Targeted the correct branch (see [PR Targeting](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
* [ ] Provided a link to the relevant issue or specification
* [ ] Followed the guidelines for [building SDK modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules)
* [ ] Included the necessary unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
* [ ] Added a changelog entry to `CHANGELOG.md`
* [ ] Included comments for [documenting Go code](https://blog.golang.org/godoc)
* [ ] Updated the relevant documentation or specification
* [ ] Reviewed "Files changed" and left comments if necessary 
* [ ] Confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed `!` in the type prefix if API or client breaking change
* [ ] confirmed all author checklist items have been addressed 
* [ ] reviewed state machine logic
* [ ] reviewed API design and naming
* [ ] reviewed documentation is accurate
* [ ] reviewed tests and test coverage

### CODE REVIEW

**Review by mpoke — CHANGES_REQUESTED** [review]
@faddat Thanks for your contribution. Note that `github.com/cosmos/cosmos-sdk/types/errors` is deprecated in SDK 0.47 and it should be removed completely.

**Comment by faddat** [comment]
This is for the 45 version hub sir, just like this other one.  

* https://github.com/cosmos/interchain-security/pull/920

Same as this:

* https://github.com/osmosis-labs/osmosis/pull/5065

The goal is to make the code review for and transition to sdk 47 as smooth as possible. 

Additionally, @mpoke if you think this is a PR into 47, then it would never pass ci and would not fall into the rules you yourself outlined for contributors. 

Suggest you familiarize yourself with the errors module

**Comment by mpoke** [comment]
@faddat I assumed that you're trying to fix this existing issue https://github.com/cosmos/gaia/issues/1786. That's the reason we first open issues. An issue should clearly state what the problem is. Discussions on the issue are necessary to assess the importance of the problem (set priorities) and the potential solutions.

In this particular case, I do not see the benefit of fixing  https://github.com/cosmos/gaia/issues/1786 halfway. The issue is that `github.com/cosmos/cosmos-sdk/types/errors` is deprecated in v0.47, which means removing it is a prerequisite of the upgrade. Note that https://github.com/cosmos/gaia/issues/1786 is part of a larger EPIC https://github.com/cosmos/gaia/issues/2413 that tracks the Gaia upgrade to v0.47. Could you please motivate why would this PR "ease the transition to 0.47"?

**Comment by faddat** [comment]
Hi there @mpoke I am not trying to fix an existing issue. 

@mpoke, I have not seen a single chain, zero, fully eliminate the use of that packafe and @mpoke, I can't actually say it is deprecated sir. As you must be aware I am a fan of very tight linting and I've not seen that deprecation notice, EXCEPT when using calls to:

* Wrap
* Wrapf
* Register

Do you have evidence to back your claims?

I also believe that you and others have informed me that cosmoshub v10 will use sdk 45.  So why not adopt the modular sdk features that make migration easier in the long run?


**why this makes moving to 47 easier**

This makes moving to 47 easier by reducing one large component of the typical changeset of an upgrade to 47.

**why you're wrong about the nature of the deprecation**

Go look at:

* github.com/cosmos/interchain-security/pull/869 

... one of the five PR's Notional made to upgrade ICS, that you closed.  Never fear, the sixth is here:

* https://github.com/cosmos/interchain-security/pull/923

.....do they both pass linting?

Want to make them fail linting with deprecation warnings?

Change these:

* Wrap
* Wrapf
* Register

Back to how they were before, and boom, yep, deprecation warning. 

Why would it pass linting if your claims are true?

Ah, the fact of the matter is that your claims are false, and that these calls:

* Wrap
* Wrapf
* Register

Are what matters.

...and that is why Notional begins work on 47 upgrades with very, very strict linting:

* https://github.com/osmosis-labs/osmosis/issues/5109

**Comment by faddat** [comment]
yo Mr. @mpoke I would indeed like to get renewed feedback on this one.  Thanks

**Review by mpoke — APPROVED** [review]
Approval. The SDK team confirmed that, while the general error types may be deprecated in the future, for now it is fine to use them. The goal is for Gaia to define its own general errors. I'll open a separate issue to deal with this later.

**Comment by faddat** [comment]
that isn't what you said sir.  You said that the errors code in the sdk had been deprecated.

You did not say that there was a goal for Gaia to define her own errors.  These are fundamentally different things, which would result in others working on the hub taking fundamentally different actions.

Did you check previously?

**Review by MSalopek — APPROVED** [review]
LGTM

**Pull request merged**
