### PR TITLE
Adds ATOMScan blockchain explorer

### PR DESCRIPTION
**Pull request by CrackLord**
## Description

I'm the creator of this blockchain explorer for Cosmos and would love to see it featured in this list of blockchain explorers.
______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/gaia/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Comment by tac0turtle** [comment]
hey could you add this to the main branch instead? I believe you will have to make a new pr off that branch.

**Comment by CrackLord** [comment]
Closing to make a new PR from main branch as advised.

**Comment by CrackLord** [comment]
> hey could you add this to the main branch instead? I believe you will have to make a new pr off that branch.

Hmm, are you sure the main branch contains this documentation that is on the website? I can't find the file for this list of blockchain explorers on the main branch.

**Comment by tac0turtle** [comment]
ah i will be migrating some docs so you may have to wait a couple days.

**Comment by CrackLord** [comment]
Ah no problem. It'd be nice if you could leave a comment here when you've migrated that part, but no worries :).

**Comment by CrackLord** [comment]
Hey, I see that you’re still updating docs on master from some other PRs, is it possible to have this one merged into master now?

**Comment by tac0turtle** [comment]
could you resubmit the PR please, i will merge it right away

**Comment by CrackLord** [comment]
Oh, I just realized someone already added it! Check before assuming anything eh!

Never mind then, thank you!

**Pull request closed without merging**
