### PR TITLE
No longer adding seeds to config.toml

### PR DESCRIPTION
**Pull request by faddat**
Correction: we no longer explain adding seeds to config.

## Description

- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/develop/CONTRIBUTING.md#pr-targeting))

- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote tests
- [x] Updated relevant documentation (`docs/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md` (did not seem changelog-worthy)
- [ ] Reviewed `Files changed` in the github PR explorer

### CODE REVIEW

**Review by tac0turtle — APPROVED** [review]

**Comment by zmanian** [comment]
You dont?

**Comment by tac0turtle** [comment]
You still have to add seeds. He changed the readme to add it through the cmd line.

**Comment by faddat** [comment]
@zmanian basically, the idea is to make automation easier and first time setup of a node easier, as well. 

Run an idea past you:

What about removing getting rid of config.toml?

It is full of things that should probably be set once in a blockchain's source code, and other things that would work just as well as env vars or flags.

Same goal:  Make Tendermint/Cosmos nodes easier to run and administer.

**Comment by zmanian** [comment]
I am strongly in favor of making config.toml either optional or have defaults that work well.

**Comment by tac0turtle** [comment]
> I am strongly in favor of making config.toml either optional or have defaults that work well.

We should make the sdk overwrite the config.toml with defaults. I don't think this would be hard. 

1. We create a doc with some seed nodes.
2. Write some code to inject it into the `seeds` section. 
3. Fetch Genesis from seed node RPC.
4. Sit back and relax.

**Comment by faddat** [comment]
Step #4 sounds delightful.

**Pull request closed without merging**
