### PR TITLE
Add goreleaser

### LINKED ISSUE #36: Release Binaries
We should release binaries when we tag versions so users don't need the go toolchain.

@melekes suggests using https://goreleaser.com/

### PR DESCRIPTION
**Pull request by adrianbrink**
closes #36

### CODE REVIEW

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/pull/774#issuecomment-341758206

**Comment by melekes** [comment]
This is as deterministic as running go build on your machine. It could be affected by existing env variables possibly.

**Comment by zramsay** [comment]
this is outdated now, see #72 instead

**Comment by zramsay** [comment]
to be handled by jenkins

**Pull request closed without merging**
