### PR TITLE
Fix rocksdb build tag usage

### PR DESCRIPTION
**Pull request by faddat**
this replaces the obsolete tecbot/gorocksdb library with the cosnmosified version.  

Alternative to this is an update + release to tm-db.  Maybe just a release.

### CODE REVIEW

**Comment by zmanian** [comment]
I don't understand the purpose of this PR?

**Comment by zmanian** [comment]
It looks like adding an unused dependency to go.mod

**Comment by faddat** [comment]
it is true!  It looks that way.  However, without that....



```bash
go install -tags rocksdb ./...
```

does not work because tecbot/rocksdb is quite out of date and imported by tm-db v0.6.6.

Also, I am making several of these currently and firing them off undocumented like:

```bash
gh pr create
```

**Comment by faddat** [comment]
https://github.com/tendermint/tm-db/blob/06fdc12b3cc0ff8eb87ec0cd0b5daa9cb5091d2b/go.mod#L41

... is better, I'll amend

**Comment by faddat** [comment]
Probably would also help if I were to say:

Works towards: #1134

**Review by tac0turtle — APPROVED** [review]
utACK, did test this? I know cosmos is on a newer version of rocks.

**Comment by faddat** [comment]
I've tested it.  I think all it sidesteps is the outdated version in the newest release of tm-db.

So could be solved with a new release of tm-db or also using the latest commit hash of tm-db.

Adding one more bit now, just using v1.1.1 of gorocksdb from cosmos.  mildly cleaner.

**Comment by okwme** [comment]
Feels dangerous to be overwriting upstream dependencies. As you mentioned the correct way would be for tm-db to update and to incorporate those updates. Is there any reason why this can't wait for then?

**Comment by tac0turtle** [comment]
tm-db has merged the work just not cut a release. Not sure when that will happen, that repo is deprecated more or less

**Comment by faddat** [comment]
Marko, tm-db is deprecated?

Can you tell me more?

Thanks!

@okwme -- this has been used on several chains successfully.  It dramatically improves sync speed and query rate.  For gaia, we can hit the trifecta-- state sync with rocksdb.   And then it utterly flies.

For me, my specific use case for this has been ibc relaying.  The difference is pretty extreme.

**Comment by zmanian** [comment]
I'm feeling more in favor of merging this based on other usage of rocksdb I see in the ecosystem.

**Review by okwme — APPROVED** [review]

**Review by zmanian — APPROVED** [review]

**Review by okwme — APPROVED** [review]

**Pull request merged**
