### PR TITLE
DOCS: Fix params broken links

### PR DESCRIPTION
**Pull request by nooomski**
#1245 got merged a little tooooo quickly. Was under the incorrect impression the `docs/governance/param-changes` folder was not being used so didn't fix those links. This should solve those.

@mmulji-ic , keep in mind not to put the `docs/governance/param-changes` on the ignore list in the config. Also let me know if you need me to just get started on it.

### CODE REVIEW

**Comment by nooomski** [comment]
Ehhh, why is it showing 24 files changed? Should be ~4 or 5. Didn't #1245 already get merged?

**Comment by nooomski** [comment]
Added ignore tags to each archived / historical file that the link checker should skip. Should be good to test @mmulji-ic

**Review by okwme — APPROVED** [review]
looks like it's passing 🎉
why do these historical markdowns need to be skipped? they have broken links that should be kept for historical reasons?

**Comment by nooomski** [comment]
@okwme almost all the docs where the link checker is skipped are currently offline, mostly because they're outdated. 
The old proposals definitely have old links that we don't want to update because the proposals are historical. 
There's also a lot of translated content that is currently so outdated it's not online (afaik).

An overview of folders I've skipped:
```
docs/migration
docs/governance/proposals
docs/zh
docs/es
docs/ko
```

And individual files: 
```
docs/governance/state-of-cosmos-governance-2021.md (historical)
docs/hub-tutorials/deploy-testnet.html (this one is outdated and needs a complete revisit as per #1244 )
```

Two links in `docs/resources/ledger.md` were working fine but kept getting marked as 403 to which I could find no workaround, so those two links contain tags so they get skipped. Not the cleanest solution unfortunately.

**Pull request merged**
