### PR TITLE
Add Permissioned CosmWASM to hub roadmap

### PR DESCRIPTION
**Pull request by jackzampolin**
🙏

### CODE REVIEW

**Review by tac0turtle — APPROVED** [review]
Lgtm

**Comment by zmanian** [comment]
I'd like to get some record of Lido's use case for cosmwasm on the Hub somewhere.

**Comment by jackzampolin** [comment]
I also think it would be cool to have DAO DAO on the hub to make it the best place to manage daos in the interchain

**Review by okwme — APPROVED** [review]

**Comment by ethanfrey** [comment]
I would love to support this from Confio's side.
We should have a Cosmos SDK 0.44 compatible wasmd 1.0 release within a month.
Which is my prerequisite to recommend it to go to the hub for security/stability.
(Welcome more auditors/eyes on the Go side)

This was the original intention of the Cosmos Hub Community Spend proposal in summer 2020, and very happy to complete that work.

**Comment by vshvsh** [comment]
> I'd like to get some record of Lido's use case for cosmwasm on the Hub somewhere.

Lido does want to have an ecosystem-aligned place to deploy its smart contracts and Hub looks like the best fit. Will have more color on that later when we're out of the upgrade procedure for Terra liquid staking which consumes a lot of focus.

**Pull request merged**
