### PR TITLE
Upgrade golangci-lint to latest release (1.19.1)

### PR DESCRIPTION
**Pull request by alessio**
- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote tests
- [ ] Updated relevant documentation (`docs/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Reviewed `Files changed` in the github PR explorer

______

For Admin Use:
- Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge PR #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Review by alexanderbez — CHANGES_REQUESTED** [review]
Instead of pinning to a specific version, why not just use `go get ...@latest`?

**Comment by alessio** [comment]
> Instead of pinning to a specific version, why not just use go get ...@latest?

Thanks for the question @alexanderbez, I apologise for not providing a rationale beforehand. The reason behind this approach is that `go get`ting `golangci-lint` would cause `go.{mod,sum}` to be polluted with dependencies that are not necessary to build `gaia`.

**Comment by alexanderbez** [comment]
> > Instead of pinning to a specific version, why not just use go get ...@latest?
> 
> Thanks for the question @alexanderbez, I apologise for not providing a rationale beforehand. The reason behind this approach is that `go get`ting `golangci-lint` would cause `go.{mod,sum}` to be polluted with dependencies that are not necessary to build `gaia`.

Correct sir, hence for `runsim` we `(cd /tmp && go get ...)`. We should do the same here.

**Comment by alessio** [comment]
I'm unsure. `$TMPDIR` is defined in Make's manual though it's on the makefile to ensure it exists beforehand. I've updated the installer script to automatically detect and download `golangci-lint`'s latest release instead. Please have a look @alexanderbez

**Review by alexanderbez — APPROVED** [review]
testedACK

**Pull request merged**
