### PR TITLE
WIP: update release note

### PR DESCRIPTION
**Pull request by yaruwangway**
- [ ] backport release 
       relevant issue: https://github.com/cosmos/gaia/issues/1122
       if let bot do the backport release ?
- [ ] major release
- [ ] point release
- [ ] release candidate release

### CODE REVIEW

**Comment by yaruwangway** [comment]
@mmulji-ic , this pr shows the way we did for releasing v6.0.1

**Comment by okwme** [comment]
How will the new [theta-release](https://github.com/cosmos/gaia/pull/1219) branch use the new system?

**Comment by yaruwangway** [comment]
> How will the new [theta-release](https://github.com/cosmos/gaia/pull/1219) branch use the new system?

Since this [theta-release branch](https://github.com/cosmos/gaia/pull/1219) is before release, and is used for dev testnet, we can create a branch called `dev-testnet`, we can either create different dev-testnet branches before different releases, or only one dev-testnet branch, and tag there different different versions. The latter might be easier for Hypha to track and automate the deployment.

**Comment by yaruwangway** [comment]
@okwme @mmulji-ic 
How about From v7, we keep three evergreen branches 
- `main`: allows improvement, bug fix to merge there
- `dev-testnet`: this branch keeps tracking a version before RC and is used for dev-testnet tracking (for better auto build and deploy for testnet).
- `release` branch, only tracking releases, based off v6 branch, we check out, rc v7 branch, and do rc release which is merged from `dev-testnet` and when release v7.0.1, we checkout based on v6 a new branch, v7.0.x, and merge the rc branch to this branch, tag v7.0.1. (if the rc is not ready to merge, any fix of rc can checkout from rc, fix, and merge to rc branch, main and dev-testnet)
 after release, the release should be merged to dev-testnet as well.

so there are 3 branches based off `v6.0.x`: `v7.0.x`, `v7-rc`, and `dev-testnet`, `dev-testnet` will cherry pick from main, when `dev-testnet` ready,  it will be merged to `v7-rc`, when `v7-rc` ready, it will be merged to release `v7.0.x`, v7.0.x will also merge back to dev-testnet to get ready to next dev-testnet. and also merge back to main maybe..

During dev-testnet, rc or releases, any fix should happen in a branch based off rc or directly on dev-testnet.
release-process

**Comment by okwme** [comment]
release-process (2)

**Comment by okwme** [comment]
moving work into #1327

**Pull request closed without merging**
