### PR TITLE
Update CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by faddat**
Make more real

### CODE REVIEW

**Comment by mmulji-ic** [comment]
Morning @faddat, the code of conduct is being reviewed and input is being sought a number of parties. In any incarnation, action should be taken against anyone who breaches it, not a subset from org A or org B. Should universally apply. Am chasing the status and will get back to you asap.

**Comment by faddat** [comment]
No.

The code of conduct is completely useless. It is effectively a lie to the community. We need to delete it or merge the modified version because we should tell the truth or expect that we are going to lose the communities trust.

By the way just because I think that proposal 82 is a good idea doesn't mean I'm your puppet, I'm also not the puppet of AIB.

**Comment by jackzampolin** [comment]
I also concur that the code of conduct no longer serves any purpose

**Comment by jackzampolin** [comment]
Closing this in favor of #1893

**Pull request closed without merging**
