### PR TITLE
gofumpt and automatic linting for gaia v2

### PR DESCRIPTION
**Pull request by faddat**
Gofumpted gaia v2 and added linting.

#1449 

- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote tests
- [ ] Updated relevant documentation (`docs/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Reviewed `Files changed` in the github PR explorer

______

For Admin Use:
- Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge PR #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Comment by faddat** [comment]
Good deal more work to be done here to pass the linter.  Converting to draft for now.

**Comment by okwme** [comment]
thanks for opening @faddat , going to close in place of #1547 which focuses on reproducing linting settings of the cosmos sdk

**Comment by okwme** [comment]
re-opening based on last comment from #1547

**Comment by okwme** [comment]
opened a new issue related to stable release policy (#1549).
appreciate the work @faddat but these changes don't make sense to merge into those versions unless they're going to be part of a new release of those versions and EOL should only be bypassed by security updates.

**Pull request closed without merging**
