### PR TITLE
Fix: Add seed nodes to init.go for greater ease of use

### LINKED ISSUE #678: Embed Seeds
## Summary

Finding seeds is a pain.

## Problem Definition

* Chasing down seeds increases "time to fully operational node". 

## Proposal

We can modify gaia to pass seeds when it sets up then init command, and for the sdk to accept seeds then, as well.  The seeds need to go to InterceptSeedsPreRunHandler, I think.  During the init step, it seems that we can override default values in config.toml.

```go
// InterceptConfigsPreRunHandler performs a pre-run function for the root daemon
// application command. It will create a Viper literal and a default server
// Context. The server Tendermint configuration will either be read and parsed
// or created and saved to disk, where the server Context is updated to reflect
// the Tendermint configuration. The Viper literal is used to read and parse
// the application configuration. Command handlers can fetch the server Context
// to get the Tendermint configuration or to get access to Viper.
func InterceptConfigsPreRunHandler(cmd *cobra.Command) error {
	serverCtx := NewDefaultContext()

	// Get the executable name and configure the viper instance so that environmental
	// variables are checked based off that name. The underscore character is used
	// as a separator
	executableName, err := os.Executable()
	if err != nil {
		return err
	}

	basename := path.Base(executableName)

	// Configure the viper instance
	serverCtx.Viper.BindPFlags(cmd.Flags())
	serverCtx.Viper.BindPFlags(cmd.PersistentFlags())
	serverCtx.Viper.SetEnvPrefix(basename)
	serverCtx.Viper.SetEnvKeyReplacer(strings.NewReplacer(".", "_", "-", "_"))
	serverCtx.Viper.AutomaticEnv()

	// intercept configuration files, using both Viper instances separately
	config, err := interceptConfigs(serverCtx.Viper)
	if err != nil {
		return err
	}

	// return value is a tendermint configuration object
	serverCtx.Config = config
	if err = bindFlags(basename, cmd, serverCtx.Viper); err != nil {
		return err
	}

	var logWriter io.Writer
	if strings.ToLower(serverCtx.Viper.GetString(flags.FlagLogFormat)) == tmcfg.LogFormatPlain {
		logWriter = zerolog.ConsoleWriter{Out: os.Stderr}
	} else {
		logWriter = os.Stderr
	}

	logLvlStr := serverCtx.Viper.GetString(flags.FlagLogLevel)
	logLvl, err := zerolog.ParseLevel(logLvlStr)
	if err != nil {
		return fmt.Errorf("failed to parse log level (%s): %w", logLvlStr, err)
	}

	serverCtx.Logger = ZeroLogWrapper{zerolog.New(logWriter).Level(logLvl).With().Timestamp().Logger()}

	return SetCmdServerContext(cmd, serverCtx)
}
```
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

### PR DESCRIPTION
**Pull request by faddat**
Closes: #678 

## Description

This PR embeds seed nodes into init.go in gaia and increases the default setting for GAIAD_P2P_INBOUND_PEERS.  

There are two objectives:

1) Make it easier for people to run Gaia nodes
2) Increase connectivity in Gaia's peer to peer network to lower sync times. 
______

For contributor use:

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
- [x] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [x] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/main/README.md#merging-a-pr))

### CODE REVIEW

**Comment by faddat** [comment]
We may also wish to remove some things from this file, or add a download to it per #677

**Comment by faddat** [comment]
I need to clean this up more, there's still some cruft in it.

**Comment by faddat** [comment]
Hey, for the time being, I am going to close this.  I am not satisfied with its clean-level, though I do think it's a great idea from a user perspective.

**Comment by mpoke** [comment]
@faddat Could you please add some context why this PR was opened again?

**Comment by mpoke** [comment]
@faddat Thanks for the contribution. We'll close this issue as we prefer to not hardcode seeds info into the gaiad binary.

**Comment by faddat** [comment]
Any chance of reconsidering that?

Baking in the seeds makes setup much easier. 

However, if we don't want to reconsider that part, can we you please dramatically increase the inbound peers?

There was a network event tonight reported by stakelab, and I think that this is that.

**Pull request closed without merging**
