### PR TITLE
Enhancements to Documentation Clarity and Precision

### PR DESCRIPTION
**Pull request by joaolago1113**
I've made some corrections to typos and grammatical errors across various documentation files in the project. Here's a brief overview of the changes:

1. **Formatting and Typo Corrections**: Corrected 'Formating' to 'Formatting' and 'teh' to 'the' in `docs/governance/formatting.md`.
2. **Clarifying Fee Parameters**: Fixed typos such as 'importantht' to 'important', refined phrasing for non-negative amounts, and removed redundancy in 'Node Nodes' in `docs/modules/globalfee.md`.
3. **Validator Security Section**: Changed 'attacked' to 'attack' for better clarity in `docs/validators/security.md`.
4. **Cosmos Hub Archives**: Amended 'to makes' to 'to make' in `docs/resources/archives.md`.
5. **General Documentation Corrections**: Addressed various grammatical errors in `docs/resources/genesis.md`, `docs/roadmap/README.md`, `third_party/proto/cosmos/staking/v1beta1/query.proto`, `docs/resources/ledger.md`, `docs/gtm-interchain.md`, `RELEASE_PROCESS.md`, and `CONTRIBUTING.md`.

Thanks for the opportunity to contribute! I hope these edits help in making the documentation clearer for everyone.

### CODE REVIEW

**Review by zmanian — APPROVED** [review]
Probably airdrop farming but legit typo fixes

**Comment by joaolago1113** [comment]
@zmanian Thanks! I really do want to add value and make a genuine effort to find issues because I have immense respect for the dedication evident by the maintainers of these open-source crypto projects. Sometimes I catch syntax issues in example code, other times it's incorrect commands in guides... this time, it was refining the documentation. Appreciate being a part of this!

**Review by p-offtermatt — APPROVED** [review]
LGTM, thanks for contributing!

**Review by mmulji-ic — APPROVED** [review]

**Comment by mmulji-ic** [comment]
Thanks @joaolago1113 !

**Pull request merged**
