### PR TITLE
fix: use client/v2 v2.0.0-beta3; fix broken client.toml usage

### PR DESCRIPTION
**Pull request by MSalopek**
Fixes a bug discovered during testing.

The CLI would ignore the variables from `client.toml` which forced operators to always use `--node <IP:port>` command line options.

The fix consists of changing `root.go` cmd wiring and updating `cosmossdk.io/client/v2` [v2.0.0-beta3](https://github.com/cosmos/cosmos-sdk/releases/tag/client%2Fv2.0.0-beta.3). The application does not use depinject.

Related:
* https://github.com/cosmos/cosmos-sdk/issues/20689
* https://github.com/cosmos/cosmos-sdk/pull/19646
* https://github.com/cosmos/cosmos-sdk/issues/18310
* example: https://github.com/cosmosregistry/chain-minimal/pull/143

### CODE REVIEW

**Comment by p-offtermatt** [comment]
Is there any automated testing we have that would help us confirm whether this fixes the issue, or do we have to check manually?

**Comment by MSalopek** [comment]
> Is there any automated testing we have that would help us confirm whether this fixes the issue, or do we have to check manually?

Tests are with Hypha, we're migrating parts of it [here](https://github.com/cosmos/gaia/pull/3205).
Re-wiring our e2e tests it not feasible at this point since new features are already in the pipeline.

Easiest way to test is to spin up a local gaia with non-default API port (`!= 26657`), update the `client.toml` and try making queries without specifying `--node`.

E.g.
```
// client.toml
node = "tcp://localhost:26658"
```

Before the fix:
```shell
gaiad status
// fails with node not available on 127.0.0.1:26657 [the default!] -- node is actually on 26658

gaiad status --node tcp://127.0.0.1:26658
// passes
```

After the fix:
```shell
gaiad status
// passes because `node = "tcp://localhost:26658"` from config.toml gets applied
```

**Review by dusan-maksimovic — APPROVED** [review]
Administrative approval

**Review by p-offtermatt — APPROVED** [review]
Thanks for the answer. That makes sense to me, so LGTM

**Pull request merged**
