### PR TITLE
gofumpt -w -l for consistency with cosmos-sdk

### PR DESCRIPTION
**Pull request by faddat**
Per

https://github.com/cosmos/gaia/pull/1468

But here's some context:

This pr can be recreated by anyone using the following commands:

```bash
go install mvdan.cc/gofumpt@latest
gofumpt -l -w .
```

### CODE REVIEW

**Comment by faddat** [comment]
OK, up to date here.  I understand per earlier comments on an earlier PR that we'd like to follow sdk standards, is this PR desired?

**Comment by okwme** [comment]
hi @faddat 
thanks for the PR, just want to confirm we'd like to stay in sync with cosmos-sdk standards.
i found their git pre-hooks use `gofmt` [here](https://github.com/cosmos/cosmos-sdk/blob/main/contrib/githooks/README.md).
will close this PR unless it changes in the SDK

**Comment by okwme** [comment]
@marbar3778 tells me sdk does use gofumpt but there's no way to add it to CI lint apparently.
re-opening this for discussion on how to proceed.

**Comment by faddat** [comment]
We can enforce gofumpt in ci.  It is very simple, but we'd hesitated to do it in osmosis because it may make the project harder to approach.  Nonetheless, I'm in support of adding it to ci, and did so in ibc-go, here:

https://github.com/cosmos/ibc-go/pull/1418

**Comment by faddat** [comment]
I've now added enforcement of gofumpt to gaia, and ci would fail in the future if the files haven't had

```
gofumpt -w -l .
```

or such run against them.

**Comment by faddat** [comment]
Additionally, codecov is a factory for red herrings.  

In this case, this patch increases its (vague) sense of overall coverage for the project, while decreasing its (vague) sense of coverage because we check errors.

eg: it is showing a reduction in coverage, despite the code becoming safer.

**Comment by faddat** [comment]
Odd thing about response times.


https://github.com/cosmos/gaia/pull/1577

**Comment by faddat** [comment]
this is just getting silly.

I've been elected to validate the hub by my delegators.

Validators are supposed to check through the code.

I found that we were behind where we should be, linting-wise.

I solved that.

What is going on here guys?

Please don't lock this PR, it is the appropriate place for this conversation.

This is a security-enhancing PR from May 27. It is July 10.

If you do not wish my contributions to hit this repository, I understand but I need for the cosmos hub team lead, @okwme to say that so that I can inform my delegators.

**Review by tac0turtle — APPROVED** [review]
Let's get this merged. We shouldn't be letting prs sit for so long for such simple changes. It's more energetic to let it sit then merging it

**Comment by okwme** [comment]
thanks for the PR @faddat and thanks for the review @marbar3778 
merging now

**Pull request merged**
