### PR TITLE
chore: remove unneeded replace tags

### PR DESCRIPTION
**Pull request by tac0turtle**
was playing around and saw these, I don't see the point to them currently

### CODE REVIEW

**Comment by okwme** [comment]
@tac0turtle these replace tags enforce the same version of tendermint, ibc and sdk for all dependencies (liquidity module and packet forward middleware in particular). This way we're not blocked on them updating their go.mod and publishing a new version or working from a fork.

**Comment by tac0turtle** [comment]
you at least don't need two sdk replaces lol, also are you sure you need them? have you run into issues or something?

**Comment by okwme** [comment]
oh shit i think the double SDK snuck in when i was discussing the same topic on a recent PR that removed them too. thanks for pointing that out!

there should be no real issues if the underlying application uses a patch release version but why take the chance? ideally we eventually get away from redundant dependencies on modules maintained my third parties.

**Comment by glnro** [comment]
For ICS we will need [these specific replace statements ](https://github.com/cosmos/gaia/pull/1938/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6)until changes are upstreamed

**Comment by tac0turtle** [comment]
I don't think replace tags are needed with how go.mod works. Not sure if there was an issue with other modules when using specific heights though?

**Review by okwme — APPROVED** [review]
Will keep for now to ensure consistency. There may not be much danger in having slightly different versions of sub-dependencies but it feels much cleaner to ensure they're all the same.

**Comment by tac0turtle** [comment]
> There may not be much danger in having slightly different versions of sub-dependencies but it feels much cleaner to ensure they're all the same.

no this is not how go dependencies work. they grab the latest compatible version. so the parent influences what the dependencies import as well. Would recommend reading up on go mods here https://go.dev/ref/mod

**Pull request merged**
