### PR TITLE
Ibc v2 test

### PR DESCRIPTION
**Pull request by yaruwangway**
Closes: #XXX

## Description
This PR is for testing [ibc-go v2.0.0-rc0](https://github.com/cosmos/ibc-go/releases/tag/v2.0.0-rc0). 
Router module is removed in this PR.
This PR would not be merged to main.

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/main/README.md#merging-a-pr))

### CODE REVIEW

**Review by colin-axner — COMMENTED** [review]
LGTM! Thanks @yaruwangway!!

cc @adizere

**Comment by adizere** [comment]
Thanks Yaru, Colin!

I confirm prelimary tests with this binary <> Hermes works. We'd like to keep this branch around for a slightly extended period of time, eg O(weeks) until we finish testing with ibc-go v2, I hope that's OK.

**Comment by yaruwangway** [comment]
> Thanks Yaru, Colin!
> 
> I confirm prelimary tests with this binary <> Hermes works. We'd like to keep this branch around for a slightly extended period of time, eg O(weeks) until we finish testing with ibc-go v2, I hope that's OK.

Hi if further test is needed, please checkout release [v6.0.0-rc3](https://github.com/cosmos/gaia/tree/v6.0.0-rc3), and there we use ibc-go v2 with the `packet-forward-middleware` module (ibc router module).

**Comment by adizere** [comment]
> > Thanks Yaru, Colin!
> > I confirm prelimary tests with this binary <> Hermes works. We'd like to keep this branch around for a slightly extended period of time, eg O(weeks) until we finish testing with ibc-go v2, I hope that's OK.
> 
> Hi if further test is needed, please checkout release [v6.0.0-rc3](https://github.com/cosmos/gaia/tree/v6.0.0-rc3), and there we use ibc-go v2 with the `packet-forward-middleware` module (ibc router module).

Thank you. Confirm we're running with v6.0.0 RCs. Feel free to close this PR.

**Pull request closed without merging**
