### PR TITLE
deps: update several things at once (sdk, ibc-go, btcd)

### PR DESCRIPTION
**Pull request by shaspitz**
Credit to @faddat, original PR here https://github.com/cosmos/gaia/pull/2490. I just needed to add https://github.com/smarshall-spitzbart/gaia/commit/e2324f23edea1c6e31d4cb54bdfea861955ea838 to make the work mergable

## Description

This PR bumps to 

* cosmos-sdk v0.45.16-ics
* ibc-go v4.4.0

And removes some replace statements

* the btcd replace is not needed anymore after 45.15
* the dragonberry replace is not needed any more
* cosmos-sdk and ibc replaces are not needed since we are importing the right versions directly

Comet stays at 0.34.27 because 0.34.28 seems to have an issue with halting under certain conditions, and 0.34.27 is used by IBC 4.4.0.

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [x] Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] Added `!` to the type prefix if API or client breaking change
* [x] Targeted the correct branch (see [PR Targeting](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
* [ ] Provided a link to the relevant issue or specification
* [ ] Followed the guidelines for [building SDK modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules)
* [ ] Included the necessary unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
* [ ] Added a changelog entry to `CHANGELOG.md`
* [ ] Included comments for [documenting Go code](https://blog.golang.org/godoc)
* [ ] Updated the relevant documentation or specification
* [x] Reviewed "Files changed" and left comments if necessary 
* [x] Confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed `!` in the type prefix if API or client breaking change
* [ ] confirmed all author checklist items have been addressed 
* [ ] reviewed state machine logic
* [ ] reviewed API design and naming
* [ ] reviewed documentation is accurate
* [ ] reviewed tests and test coverage

### CODE REVIEW

**Comment by shaspitz** [comment]
Hey @faddat we looked into deps more and it seems that IBC go 4.4 references comet 0.34.27, see [here](https://github.com/cosmos/ibc-go/blob/405d674bd16f7fe4cb8c675b4a8c97d103903af5/go.mod#LL21C43-L21C43). Are we missing something?

In the meantime we've downgraded comet from 0.34.28 to 0.34.27 in this PR

**Comment by shaspitz** [comment]
This PR doesn't work on top of main without bumping comet, which we cannot do because of https://github.com/cometbft/cometbft/issues/773, therefore I'll make this PR a draft, it will most likely be closed.

**Comment by shaspitz** [comment]
The comet issue is not a problem after @MSalopek debugged, I've re-bumped comet to 0.24.28

**Review by MSalopek — APPROVED** [review]
LGTM!

**Review by jtremback — APPROVED** [review]
LGTM, but before we deploy this, I'd really like @glnro @yaruwangway and @mmulji-ic to double check our removal of those replace statements

**Comment by mmulji-ic** [comment]
> LGTM, but before we deploy this, I'd really like @glnro @yaruwangway and @mmulji-ic to double check our removal of those replace statements

LGTM

**Pull request merged**
