### PR TITLE
chore: tidy up imports

### PR DESCRIPTION
**Pull request by Anmol1696**
Closing #1527.

Group all imports into 3 sections: stdlib, 3rd party libs, gaia

### CODE REVIEW

**Comment by faddat** [comment]
This is another great idea.

I support merging this.

**Comment by faddat** [comment]
Anmol, I am going to merge your branch into one of mine, and it'll show up as we both did it.

Can you please let me know if the result fits with what you desire here?

How's this work for you sir?

https://github.com/cosmos/gaia/pull/1694

**Comment by Anmol1696** [comment]
Looks good to me, as long as we are making the imports and the whole code base better, that is the goal after all :)

**Comment by Anmol1696** [comment]
Closing this PR.

**Pull request closed without merging**
