### PR TITLE
use Notional's ibc-go fork so we can identify that the issue is in liquidity

### PR DESCRIPTION
**Pull request by faddat**

### CODE REVIEW

**Comment by faddat** [comment]
This won't tidy but at least it can show where the issue is.

**Comment by faddat** [comment]
Here, I'll go upstream and make a PR to the liquidity module....

**Comment by faddat** [comment]
While it is indeed in the liquidity module, please note that this PR is incomplete and may contain a bug:

https://github.com/Gravity-Devs/liquidity/pull/16

**Review by yaruwangway — APPROVED** [review]

**Comment by faddat** [comment]
Oh, I'm sorry!  I didn't know this had been approved.  Reopening.

**Comment by okwme** [comment]
this PR doesn't contain any files changes since yaru's PR was merged.
we still need to wait on Cosmos SDK v0.46 release for upstream dependencies IBC, Packet-Middleware, and Liquidity.
Going to close in place of PRs that will contain those releases when they're ready.
thanks for the PR @faddat

**Pull request closed without merging**
