### PR TITLE
R4R: Update reproducible build command

### PR DESCRIPTION
**Pull request by okwme**
to use latest reproducible build docker image from https://github.com/tendermint/images which is published on the tendermintdev dockerhub account

### CODE REVIEW

**Comment by okwme** [comment]
the old version uses go v1.15.x which freaks out when it sees the `retract` line in `go.mod`.
I think this is also why LGTM stopped working

**Comment by okwme** [comment]
I had to use that image to build the images for the release in `v6.0.2`. It should be used going forward for running
`make distclean build-reproducible`

**Comment by glnro** [comment]
Interesting...was this changed recently or always like this?

**Comment by okwme** [comment]
not sure when it got updated but we didn't follow suit ;_;

**Comment by okwme** [comment]
new docker image is here: https://github.com/tendermint/images/tree/master/rbuilder

**Comment by okwme** [comment]
old one was here: https://hub.docker.com/layers/cosmossdk/rbuilder/latest/images/sha256-0870f37eb666e4c4be9fd22892a32c70247b177008fff06f27b2fb708fe95c34?context=explore

**Comment by okwme** [comment]
updated docs, R4R @mmulji-ic

**Pull request merged**
