### PR TITLE
deps!: bump sdk

### PR DESCRIPTION
**Pull request by shaspitz**
## Description

Bumps sdk to https://github.com/cosmos/cosmos-sdk/releases/tag/v0.45.16-ics, containing https://github.com/cosmos/cosmos-sdk/pull/16097 

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [x] Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [x] Added `!` to the type prefix if API or client breaking change
* [x] Targeted the correct branch (see [PR Targeting](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
* [x] Provided a link to the relevant issue or specification
* [x] Followed the guidelines for [building SDK modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules)
* [x] Included the necessary unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
* [x] Added a changelog entry to `CHANGELOG.md`
* [x] Included comments for [documenting Go code](https://blog.golang.org/godoc)
* [x] Updated the relevant documentation or specification
* [x] Reviewed "Files changed" and left comments if necessary 
* [ ] Confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed `!` in the type prefix if API or client breaking change
* [ ] confirmed all author checklist items have been addressed 
* [ ] reviewed state machine logic
* [ ] reviewed API design and naming
* [ ] reviewed documentation is accurate
* [ ] reviewed tests and test coverage

### CODE REVIEW

**Comment by shaspitz** [comment]
Can someone sanity check me that the reason we don't need this upgrade in the ICS repo is because the sdk version dep is in a replace statement in the gaia go.mod, right?

**Comment by faddat** [comment]
Hey, I think this may be a better approach to the needed bump:

https://github.com/cosmos/gaia/pull/2490

**Comment by mpoke** [comment]
> Can someone sanity check me that the reason we don't need this upgrade in the ICS repo is because the sdk version dep is in a replace statement in the gaia go.mod, right?

@smarshall-spitzbart AFAIK, the version of SDK used when building Gaia will be the one specified in the go.mod of this repo. This means that that version will be used for other dependencies as well, e.g., ICS, IBC, PFM. The reason to upgrade ICS to this new version of SDK is for testing purposes -- the entire CI of ICS works with the SDK version in the go.mod of the ICS repo. @MSalopek could you please confirm this?

**Comment by mpoke** [comment]
@smarshall-spitzbart Note that the bump to SDK 0.45.16-ics is state machine breaking. Thus, we cannot backport to v9.0.x branch.

**Comment by mpoke** [comment]
> Hey, I think this may be a better approach to the needed bump:
> 
> #2490

@faddat Thanks for your feedback. Could you please motivate why you think that PR is a better approach?

**Review by mpoke — APPROVED** [review]
Approval

**Pull request closed without merging**
