### PR TITLE
docs: Update gov module docs

### PR DESCRIPTION
**Pull request by glnro**
This PR fulfills the documentation component of #1424 .

### CODE REVIEW

**Comment by hxrts** [comment]
This is really great. My only question is to what extent do we want to be maintaining information about gov module behavior in the gaia repo. If we've modified defaults it certainly makes sense, but if there's every a change to gov we'll need to track that and update gaia docs.

**Review by mmulji-ic — APPROVED** [review]
Great Job @glnro

**Review by LexaMichaelides — APPROVED** [review]
Looks great!

**Comment by okwme** [comment]
looks like broken links
`https://docs.tendermint.com/v0.35/tendermint-core/block-sync/` could be changed to
`https://github.com/tendermint/tendermint/blob/v0.34.x/spec/p2p/messages/block-sync.md`

`https://docs.tendermint.com/master/tendermint-core/state-sync/#` could be changed to `https://github.com/tendermint/tendermint/blob/v0.34.x/spec/p2p/messages/state-sync.md`

**Comment by okwme** [comment]
is this supposed to be targeting `okwme/docs-home` ?

**Comment by mmulji-ic** [comment]
> is this supposed to be targeting `okwme/docs-home` ?

Yes, should be doc updates only for Rho, which should get merged into main / release branch.

**Pull request merged**
