### PR TITLE
Build gaia against SDK's latest master

### PR DESCRIPTION
**Pull request by alessio**
Also drop replace statement from go.mod.

Reference: cosmos/cosmos-sdk#4687

- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote tests
- [ ] Updated relevant documentation (`docs/`)
- [ ] Added a relevant changelog entry: `clog add [section] [stanza] [message]`
- [ ] Reviewed `Files changed` in the github PR explorer

______

For Admin Use:
- Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge PR #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Comment by colin-axner** [comment]
Should we wait to merge this until [supply-genesis](https://github.com/cosmos/cosmos-sdk/pull/4686) gets merged?

**Comment by colin-axner** [comment]
Also [this](https://github.com/cosmos/cosmos-sdk/pull/4707) is causing the build issues, simapp got updated.

**Comment by alessio** [comment]
@colin-axner dixit:

> Also this is causing the build issues, simapp got updated.

I'm aware of that, I'm on it.

> Should we wait to merge this until supply-genesis gets merged?

In line of principle, `gaia` should always be buildable. @mircea-c was experiencing issues, so this should not block on cosmos/cosmos-sdk#4686 (even though of course, if that got merged first it'd be even better)

**Comment by alessio** [comment]
Closing for now, we shall address all new changes in an ensuing PR.

**Pull request closed without merging**
