### PR TITLE
fix: submission of broken invariants

### LINKED ISSUE #3345: [Bug]: Sending proof for broken invariants is not possible
## Problem

Sending a proof for a broken invaraint is not possible in current version of gaia

## Closing criteria

Submitting a proof for a broken invariant is supported

## Problem details

Submitting a proof for a broken invariant is not possible and the message is treated as an "invalid" transaction

## Gaia Version
v19.1.0

### PR DESCRIPTION
**Pull request by bermuell**
## Description

Closes: #3345 

Fix submission of broken invariants

Reason:
- passing uninitialized bankkeeper and accountkeeper when creating crisis keeper causes a failure when handling `verify invariant` messages 

 
---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [x] Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] Added `!` to the type prefix if API, client, or state breaking change (i.e., requires minor or major version bump)
* [x] Targeted the correct branch (see [PR Targeting](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
* [x] Provided a link to the relevant issue or specification
* [x] Followed the guidelines for [building SDK modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules)
* [x] Included the necessary unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
* [x] Added a changelog entry in `.changelog` (for details, see [contributing guidelines](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#changelog))
* [x] Included comments for [documenting Go code](https://blog.golang.org/godoc)
* [ ] Updated the relevant documentation or specification
* [x] Reviewed "Files changed" and left comments if necessary 
* [ ] Confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed `!` in the type prefix if API or client breaking change
* [ ] confirmed all author checklist items have been addressed 
* [ ] reviewed state machine logic
* [ ] reviewed API design and naming
* [ ] reviewed documentation is accurate
* [ ] reviewed tests and test coverage

### CODE REVIEW

**Comment by MSalopek** [comment]
Could you explain why moving the crisis keeper registration lower in the file solves the problem (or why)?

**Comment by bermuell** [comment]
> Could you explain why moving the crisis keeper registration lower in the file solves the problem (or why)?

Creation of the crisis keeper using uninitialized BankKeeper and AccountKeeper is the reason for the failures. Moving it after the initialization of these two keepers solves the issue.

**Review by mpoke — APPROVED** [review]
LGTM

**Review by MSalopek — APPROVED** [review]
LGTM

**Pull request merged**
