### PR TITLE
fumpt

### PR DESCRIPTION
**Pull request by faddat**
This runs gofumpt against the main branch

### CODE REVIEW

**Comment by faddat** [comment]
codecov is a red herring factory

**Review by tac0turtle — APPROVED** [review]
Lgtm

**Comment by faddat** [comment]
FYI, this PR is exactly the same as:

https://github.com/cosmos/gaia/pull/1512

and

https://github.com/cosmos/gaia/pull/1468

I just wish to make that clear.  

I completed this PR after doing #1579 per the request of someone here.

**Comment by faddat** [comment]
Screen Shot 2022-07-10 at 8 25 18 PM


when I append "codecov is a red herring factory" to a PR, this is what I mean

**Pull request merged**
