### PR TITLE
Backport/for v5.0.8

### PR DESCRIPTION
**Pull request by yaruwangway**
Closes: #999 
Backport v5.0.7 is already released. Changes in v5.0.7: bump cosmos-sdk version to v0.42.10.
Backport v5.0.8 will include the following changes:
- add ibc ante handler
- [update testnet](https://github.com/cosmos/gaia/issues/879)
## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/main/README.md#merging-a-pr))

### CODE REVIEW

**Comment by okwme** [comment]
looks like `go mod tidy` needs to be run to fix the conflicts in the `go.sum` file

**Comment by yaruwangway** [comment]
> looks like `go mod tidy` needs to be run to fix the conflicts in the `go.sum` file

I ran `go mod tidy`, but no changes in go.sum

**Comment by okwme** [comment]
there are still some conflicts in `go.sum` @yaruwangway want to try locally merging `release/v5.0.x` into `backport/for_v5.0.8`, resolve the conflicts and then push?

**Comment by yaruwangway** [comment]
> there are still some conflicts in `go.sum` @yaruwangway want to try locally merging `release/v5.0.x` into `backport/for_v5.0.8`, resolve the conflicts and then push?

Not sure what happened, but I rebased, should be fine now.

**Review by okwme — APPROVED** [review]

**Review by crodriguezvega — APPROVED** [review]

**Review by colin-axner — APPROVED** [review]

**Pull request merged**
