### PR TITLE
gofumpt for v3

### PR DESCRIPTION
**Pull request by faddat**
## Description

Applies gofumpt to gaia v3 to make code easier to read

#1449 same
______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/main/README.md#merging-a-pr))

### CODE REVIEW

**Comment by faddat** [comment]
Shall I fix docker, too?

**Comment by faddat** [comment]
https://github.com/cosmos/gaia/runs/6616154825?check_suite_focus=true#step:4:27

yes, we can find actual issues this way.

**Review by tac0turtle — APPROVED** [review]
LGTM

**Comment by okwme** [comment]
same as per comment from #1509:
> opened a new issue related to stable release policy (#1549).
appreciate the work @faddat but these changes don't make sense to merge into those versions unless they're going to be part of a new release of those versions and EOL should only be bypassed by security updates.

**Comment by faddat** [comment]
Except that legibility & standardization is a security update.

**Pull request closed without merging**
