### PR TITLE
feat: add support for generating and uploading binaries via Github Actions

### LINKED ISSUE #1347: Generate and upload binaries for a release using GH actions

### PR DESCRIPTION
**Pull request by jim380**
Closes: #1347 

- Add Dockerfile
- Add release.yml
- Modify Makefile

### CODE REVIEW

**Comment by tokamak-git** [comment]
hey @jim380 thanks for the pr, we have been working on our end on automating the release process as well, checkout: `https://github.com/cosmos/gaia/pull/1388/files` 

Does your pr differ?

**Comment by tokamak-git** [comment]
hey @jim380 thanks for the pr, we have been working on our end on automating the release process as well, checkout: `https://github.com/cosmos/gaia/pull/1388/files` 

Does your pr differ?

**Comment by jim380** [comment]
@tokamak-git The biggest difference I see is mine builds the binaries with Docker. Other than that, not much different.

**Comment by tokamak-git** [comment]
@jim380 I have an issue where we are specifically targeting docker #916 do take a look.
I am inclined to close this issue.

**Comment by jim380** [comment]
> @jim380 I have an issue where we are specifically targeting docker #916 do take a look. I am inclined to close this issue.

I think the issue was that you were trying to push with your personal github token and the code was expecting a token from the repo's owner. Try replacing [this line](https://github.com/cosmos/gaia/blob/04735457ee59e63e74e2b6bac32bf1144ad36448/.github/workflows/docker-push.yml#L45) with username: `${{ github.actor }}`.

**Comment by tokamak-git** [comment]
@jim380 closing in favor of #916

**Pull request closed without merging**
