### PR TITLE
docs: release testnet upgraded to v15

### LINKED ISSUE #2940: Add v15 upgrade height Cosmos Hub Testnet doc with
## Summary of Bug

The Joining Testnet page of the Cosmos Hub docs must be updated with the upgrade height for v15.

https://hub.cosmos.network/main/hub-tutorials/join-testnet.html

## Version

`main` branch of `cosmos/gaia` repo

## Steps to Reproduce

* Visit the Joining Testnet page: https://hub.cosmos.network/main/hub-tutorials/join-testnet.html
* The v15 upgrade height  should say `20,269,900`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

### PR DESCRIPTION
**Pull request by dasanchez**
## Description

Closes: #2940 

This PR updates the current version for the release testnet, `theta-testnet-001`, to Gaia v15.

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [X] included the correct `docs:` prefix in the PR title
- [X] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [X] provided a link to the relevant issue or specification
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] Confirmed the correct `docs:` prefix in the PR title
- [ ] Confirmed all author checklist items have been addressed 
- [ ] Confirmed that this PR only changes documentation
- [ ] Reviewed content for consistency
- [ ] Reviewed content for thoroughness
- [ ] Reviewed content for spelling and grammar
- [ ] Tested instructions (if applicable)

### CODE REVIEW

**Review by p-offtermatt — COMMENTED** [review]
On line 82, there is this:

```
You will need to install and configure the Gaia binary using the script below. The Cosmos Hub Public Testnet is running Gaia [`v13.0.0`](https://github.com/cosmos/gaia/releases/tag/v13.0.0).
```

I think it needs to be modified to v15, too?

**Review by p-offtermatt — COMMENTED** [review]
line 75 explains how to install go1.20, but I think v15 needs go1.21, see https://github.com/cosmos/gaia/blob/v15.0.0-rc0/go.mod

**Review by p-offtermatt — APPROVED** [review]
LGTM, thanks for the update.
I commented on a couple of places where afaict some things are not up-to-date.

**Review by MSalopek — COMMENTED** [review]
> * If you are using Fast Sync, the chain will start syncing once the first block after genesis is found among the peers. **Syncing to the current block height will take several days**.

I cannot make a comment on unchanged sections, but this one is outdated. Fastsync was disabled IIRC?

**Comment by dasanchez** [comment]
Thanks for the review @p-offtermatt @MSalopek 🙏🏽

**Review by MSalopek — APPROVED** [review]
LGTM

**Pull request merged**
