### PR TITLE
ci: run golang tests

### LINKED ISSUE #2441: Implement CI testing against main/release branches for the selected platforms.
# Problem

Gaia needs to run on multiple platforms, typically validator and end user systems will differ in terms of operating system and other hardware specifics. This initial issue is to start with this type of testing across platforms and then, over time, expand or reduce scope based on platform requirements after discussions with stakeholders, see the tracking issue for these other activities #2258 .

Emphasis is NOT on running the e2e suite on different platforms, but on running user level cli operations and those that require crypto wallets.

# Closing criteria

Gaia nightly tests are run on a number of platforms/architectures.

### PR DESCRIPTION
**Pull request by faddat**
## Description

This will run tests on multiple platforms.  

Touches on but does not close: #2441
---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [ ] Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] Added `!` to the type prefix if API or client breaking change
* [ ] Targeted the correct branch (see [PR Targeting](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
* [ ] Provided a link to the relevant issue or specification
* [ ] Followed the guidelines for [building SDK modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules)
* [ ] Included the necessary unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
* [x] Added a changelog entry to `CHANGELOG.md`
* [ ] Included comments for [documenting Go code](https://blog.golang.org/godoc)
* [ ] Updated the relevant documentation or specification
* [ ] Reviewed "Files changed" and left comments if necessary 
* [ ] Confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed `!` in the type prefix if API or client breaking change
* [ ] confirmed all author checklist items have been addressed 
* [ ] reviewed state machine logic
* [ ] reviewed API design and naming
* [ ] reviewed documentation is accurate
* [ ] reviewed tests and test coverage

### CODE REVIEW

**Comment by mmulji-ic** [comment]
@faddat if you want to start work on an issue, please request beforehand and have a convo to understand whats intended.

**Comment by faddat** [comment]
@mmulji-ic -- I assume that you'd had something more complex in mind -- this just tests multiple platforms with go test ./...

Can also implement matrix testing

**Comment by mmulji-ic** [comment]
> @mmulji-ic -- I assume that you'd had something more complex in mind -- this just tests multiple platforms with go test ./...
> 
> Can also implement matrix testing

No problems, I started working on this already, but lets have a chat tomorrow. I can tell you what I intended and we can continue on this PR.

**Comment by faddat** [comment]
cool :). 

I think it's not the same thing as what this PR does.  Basically just saw the issue and figured I would add moire multiplatformness

**Comment by mpoke** [comment]
@faddat Thank you for contributing to Gaia. To ensure a smooth workflow for all contributors, please read the contributing guidelines for this repo https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md. **_We have asked this repeatedly._** 

It is highly unprofessional to start working on an issue already assigned to somebody else. 
  
Screenshot 2023-04-26 at 09 54 12

In the future, **_please follow the guidelines, otherwise your contributions will be rejected without review_**.

**Comment by mmulji-ic** [comment]
@faddat take a look at [workflow](https://github.com/mmulji-ic/gaia/blob/main/.github/workflows/nightly-tests.yml) that I was working on. 

I think we want to change the nightly checks to run the multi-platform tests.

Also we want to reuse the `test.yml` and `sims.yml` in the nightlies.  The GH action syntax below, needs to be fixed, is that something you can continue with? 

```
name: "Nightly E2E run"
on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ main, rc/v*, release/v* ]

jobs:
  matrix-tests:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]       # We can add custom runners - https://github.com/actions/runner
    runs-on: ${{ matrix.os }}
    steps:
      - name: run-tests
        uses: cosmos/gaia/.github/workflows/test.yml@main
      - name: run-simulations
        uses: cosmos/gaia/.github/workflows/sims.yml@main

```

Note that `main` is already on `go 1.20.x`, so we should skip running tests for `go 1.19.x`.

**Comment by faddat** [comment]
Good day @mpoke 

-- I did not in fact think that this would complete the issue.  

Good day @mmulji-ic I wanna let you know that I did not intend to stop you from doing your work.  I actually figured that this would sit aside it, and enhance rigor overall. 


If that is not the case, please just let me know and I'm happy to close the pr. 

You mention repeatedly @mpoke - in what other case have I stepped over the boundary?  Thank you

**Comment by faddat** [comment]
closing due to protest from stewarding team

**Pull request closed without merging**
