### PR TITLE
Cosmos Hub with ibc-go v5 and cosmos-sdk v0.46.0

### PR DESCRIPTION
**Pull request by faddat**
Ok, so --  this PR will cause the diffs in the CI system to trigger.

Then, we will see two kinds of issues:

1) grandfathered-in stuff
2) migration stuff -- all in e2e

the solution is outlined in #1449

### CODE REVIEW

**Comment by mmulji-ic** [comment]
@faddat is this what your expecting?

> --> Running linter
> WARN [linters context] bodyclose is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
> WARN [linters context] structcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
> tests/e2e/chain.go:51:6: `newChain` is unused (deadcode)
> func newChain() (*chain, error) {
>      ^
> tests/e2e/e2e_cli_util.go:15:6: `queryGaiaTx` is unused (deadcode)
> func queryGaiaTx(endpoint, txHash string) error {
>      ^
> tests/e2e/e2e_cli_util.go:40:6: `getSpecificBalance` is unused (deadcode)
> func getSpecificBalance(endpoint, addr, denom string) (amt sdk.Coin, err error) {
>      ^
> tests/e2e/e2e_cli_util.go:75:6: `queryGaiaDenomBalance` is unused (deadcode)
> func queryGaiaDenomBalance(endpoint, addr, denom string) (sdk.Coin, error) {
>      ^
> tests/e2e/e2e_cli_util.go:102:6: `queryGovProposal` is unused (deadcode)
> func queryGovProposal(endpoint string, proposalId int) (govv1beta1.QueryProposalResponse, error) {
>      ^
> tests/e2e/genesis.go:44:6: `addGenesisAccount` is unused (deadcode)
> func addGenesisAccount(path, moniker, amountStr string, accAddr sdk.AccAddress) error {
>      ^
> tests/e2e/io.go:10:6: `copyFile` is unused (deadcode)
> func copyFile(src, dst string) (int64, error) {
>      ^
> tests/e2e/io.go:36:6: `writeFile` is unused (deadcode)
> func writeFile(path string, body []byte) error {
>      ^
> tests/e2e/keys.go:25:6: `createMemoryKey` is unused (deadcode)
> func createMemoryKey() (mnemonic string, info *keyring.Record, err error) {
>      ^
> tests/e2e/e2e_cli_util.go:82:15: G107: Potential HTTP request made with variable url (gosec)
> 	resp, err := http.Get(path)
> 	             ^
> tests/e2e/e2e_cli_util.go:106:15: G107: Potential HTTP request made with variable url (gosec)
> 	resp, err := http.Get(path)
> 	             ^
> tests/e2e/io.go:42:9: G306: Expect WriteFile permissions to be 0600 or less (gosec)
> 	return ioutil.WriteFile(path, body, 0o644)
> 	       ^
> tests/e2e/validator.go:46:21: func `(*validator).configDir` is unused (unused)
> func (v *validator) configDir() string {
>                     ^
> tests/e2e/validator.go:50:21: func `(*validator).createConfig` is unused (unused)
> func (v *validator) createConfig() error {
>                     ^
> tests/e2e/chain.go:45:6: type `chain` is unused (unused)
> type chain struct {
>      ^
> tests/e2e/validator.go:42:21: func `(*validator).instanceName` is unused (unused)
> func (v *validator) instanceName() string {
>                     ^
> tests/e2e/validator.go:162:21: func `(*validator).createKey` is unused (unused)
> func (v *validator) createKey(name string) error {
>                     ^
> tests/e2e/validator.go:30:6: type `validator` is unused (unused)
> type validator struct {
>      ^
> tests/e2e/util.go:10:6: func `decodeTx` is unused (unused)
> func decodeTx(txBytes []byte) (*sdktx.Tx, error) {
>      ^
> tests/e2e/chain.go:63:17: func `(*chain).configDir` is unused (unused)
> func (c *chain) configDir() string {
>                 ^
> tests/e2e/e2e_cli_util.go:54:6: func `queryGaiaAllBalances` is unused (unused)
> func queryGaiaAllBalances(endpoint, addr string) (sdk.Coins, error) {
>      ^
> tests/e2e/genesis.go:20:6: func `getGenDoc` is unused (unused)
> func getGenDoc(path string) (*tmtypes.GenesisDoc, error) {
>      ^
> tests/e2e/keys.go:39:6: func `createMemoryKeyFromMnemonic` is unused (unused)
> func createMemoryKeyFromMnemonic(mnemonic string) (*keyring.Record, error) {
>      ^
> tests/e2e/validator.go:55:21: func `(*validator).init` is unused (unused)
> func (v *validator) init() error {
>                     ^
> tests/e2e/validator.go:88:21: func `(*validator).createNodeKey` is unused (unused)
> func (v *validator) createNodeKey() error {
>                     ^
> tests/e2e/chain.go:67:17: func `(*chain).createAndInitValidators` is unused (unused)
> func (c *chain) createAndInitValidators(count int) error {
>                 ^
> tests/e2e/chain.go:120:17: func `(*chain).createValidator` is unused (unused)
> func (c *chain) createValidator(index int) *validator {
>                 ^
> tests/e2e/keys.go:11:6: func `createMnemonic` is unused (unused)
> func createMnemonic() (string, error) {
>      ^
> tests/e2e/validator.go:202:21: func `(*validator).signMsg` is unused (unused)
> func (v *validator) signMsg(msgs ...sdk.Msg) (*sdktx.Tx, error) {
>                     ^
> tests/e2e/chain.go:26:2: var `cdc` is unused (unused)
> 	cdc            codec.Codec
> 	^
> tests/e2e/chain.go:93:17: func `(*chain).createAndInitValidatorsWithMnemonics` is unused (unused)
> func (c *chain) createAndInitValidatorsWithMnemonics(count int, mnemonics []string) error {
>                 ^
> tests/e2e/validator.go:171:21: func `(*validator).buildCreateValidatorMsg` is unused (unused)
> func (v *validator) buildCreateValidatorMsg(amount sdk.Coin) (sdk.Msg, error) {
>                     ^
> tests/e2e/validator.go:127:21: func `(*validator).createKeyFromMnemonic` is unused (unused)
> func (v *validator) createKeyFromMnemonic(name, mnemonic string) error {
>                     ^
> tests/e2e/validator.go:104:21: func `(*validator).createConsensusKey` is unused (unused)
> func (v *validator) createConsensusKey() error {
>                     ^
> exit status 1
> make: *** [lint] Error 1
>

**Comment by faddat** [comment]
Yeah, so like, it actually triggers if the files actually change but it should trigger all the time and the linter should be set to "latest" so it can help us secure the hub. 

Per #1449 -- the diffs that is used as the run condition shouldn't be used that way.

**Comment by faddat** [comment]
The linter doesn't run even though I changed go files

Screen Shot 2022-07-31 at 11 24 26 PM

Documented in:

* #1449

**Comment by okwme** [comment]
found the issue of linter not running and merged https://github.com/cosmos/gaia/pull/1611 to add checkout so linter runs.
The PR also contains a lot of `//nolint:unused` for items contained in E2E tests (it's strange these all seem to be false positives. Something to do with how tests are considered in the unused logic. @faddat said he's making a PR on this as well)

**Comment by okwme** [comment]
thank you @faddat !!!
i'm gonna start adding back the IBC E2E tests now

**Pull request merged**
