### PR TITLE
Build against cosmos-sdk v0.42.0

### PR DESCRIPTION
**Pull request by alessio**
______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/main/README.md#merging-a-pr))

### CODE REVIEW

**Comment by zmanian** [comment]
There isn't any reason not to do a `gaia 4.*` release against `cosmos-sdk 0.42`. It's not a consensus breaking change for gaia.

Other zones that use other bech32 prefixes need to know that it would cause consensus to diverge if all nodes don't upgrade.

**Comment by tac0turtle** [comment]
The question here is more focused on the sdk. They would like to drop support for 0.41. This can only be done if its backwards compatible with 0.41 for the hub, IMO

**Comment by zmanian** [comment]
I don't who "they" is in @marbar3778 comment.

For gaia 0.42 is a backwards compatible release.

For any SDK user the overrides the bech32 HRP it isn't backwards compatible.

**Comment by tac0turtle** [comment]
Sorry the sdk team: https://github.com/cosmos/cosmos-sdk/pull/8784

```
The 0.42 release series is going to supersede the 0.41 release series. The Cosmos Hub can seemingly upgrade to 0.42 anytime.
```

**Comment by zmanian** [comment]
yes.

**Review by shahankhatch — APPROVED** [review]

**Pull request merged**
