### PR TITLE
Make format

### PR DESCRIPTION
**Pull request by faddat**
This PR changes our command `make format` so that it matches ibc-go and the cosmos-sdk.

`make format` will now fun `gofumpt -w -l` and `golangci-lint run ./... --fix`

It also pulls in a solution to #1527 from @anmol1696 because we actually changed the ibc-go Makefile (and then the cosmos-sdk Makefile) while working on similar import grouping / code consistency questions. 

(basically I figured they might as well go in the same PR)

### CODE REVIEW

**Review by Anmol1696 — APPROVED** [review]
LGTM

**Comment by faddat** [comment]
Awesome I'm glad that it put together the two techniques that we were chasing.

Really happy to see another hub contributor 🙂

**Review by tac0turtle — APPROVED** [review]
LGTM

**Comment by faddat** [comment]
Please let me know if this is desired.

**Review by okwme — APPROVED** [review]

**Pull request merged**
