### PR TITLE
deps!: bump PFM to v4.1.0

### LINKED ISSUE #2669: packet-forward-middleware not working as expected
## Summary of Bug

When I forward ibc transfer tx to osmosis via cosmoshub, if the amount is greater than the maximum value of int64, the estimated will fail, this problem exists in both mainnet and testnet

Before the v4.0.6 of packet-forward-middleware, if ibc transfer amount was greater than the maximum value of int64, the conversion would overflow, causing the [code](https://github.com/strangelove-ventures/packet-forward-middleware/blob/ac89f66ccba85d6bf3a142d01bb57f0f05d6d659/router/keeper/keeper.go#L307C12-L307C17) to panic, and tx would fail

Related issues: 
[gaia #2553](https://github.com/cosmos/gaia/pull/2553)
[packet-forward-middleware #78](https://github.com/strangelove-ventures/packet-forward-middleware/pull/78)

## Version

gaia: v10.0.2(Latest)
gaia: v11.0.0(Pre-release)

## Steps to Reproduce

Send ibc transfer tx to chainA(Any chain with which cosmoshub has created an ibc channel), receiver is cosmoshub, amount must be greater than maximum value of int64, and fill tx memo with [forward data](https://github.com/strangelove-ventures/packet-forward-middleware/tree/v4.0.5#minimal-example---chain-forward-a-b-c) (for example, forward to osmosis/evmos/kava)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

### PR DESCRIPTION
**Pull request by mpoke**
## Description

Closes: https://github.com/cosmos/gaia/issues/2669

Bumps PFM to https://github.com/cosmos/ibc-apps/releases/tag/middleware%2Fpacket-forward-middleware%2Fv4.1.0

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [x] Targeted the correct branch (see [PR Targeting](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [x] Provided a link to the relevant issue or specification
- [x] Reviewed "Files changed" and left comments if necessary 
- [ ] Confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] Confirmed all author checklist items have been addressed
- [ ] Confirmed that this PR does not change production code

### CODE REVIEW

**Comment by mpoke** [comment]
@jtieri Could you please confirm that it's safe to backport this PR to Gaia v10 and v11?

**Comment by yaruwangway** [comment]
The upgrade test failed 
```
2:24PM INF Replay last block using real app module=consensus
2:24PM INF applying upgrade "v12" at height: 15
2:24PM INF Starting module migrations...
panic: no migrations found for module packetfowardmiddleware: not found
```
The reason is PFM 4.0.6 has a migration, you can see the module consensus version is increased and there is a migration.https://github.com/strangelove-ventures/packet-forward-middleware/compare/v4.0.5...v4.0.6
However, the migration is not registered. here is a ref how to register the migration. [ref1](https://github.com/cosmos/gaia/blob/1bab49113bebb1e26634645531a30613bbad03f1/x/globalfee/module.go#L130), [ref2](https://github.com/yaruwangway/packet-forward-middleware/blob/ad91e9eab60a59714665d66af80590364c6d57c7/router/module.go#L117)

besides, the PFM migration seems not a migration, it is just a func takes old genState , return a new genState.

I tested this with [a fake migration, and registered it in PFM module.go]( https://github.com/strangelove-ventures/packet-forward-middleware/compare/v4.0.6...yaruwangway:packet-forward-middleware:fix-upgrade?expand=1), the upgrade test passes.

**Comment by MSalopek** [comment]
Setting to draft because we cannot integrate `v4.0.6` - we need to wait for `v4.0.7`.
`v4.0.6` has ain issue with `ConsensusVersion` and migration registration.

**Comment by mpoke** [comment]
> Setting to draft because we cannot integrate `v4.0.6` - we need to wait for `v4.0.7`.
> `v4.0.6` has ain issue with `ConsensusVersion` and migration registration.

Updated to [4.1.0](https://github.com/cosmos/ibc-apps/releases/tag/middleware%2Fpacket-forward-middleware%2Fv4.1.0)

**Review by yaruwangway — APPROVED** [review]

**Review by mmulji-ic — APPROVED** [review]

**Pull request merged**
