### PR TITLE
WIP: add back antehandler

### PR DESCRIPTION
**Pull request by yaruwangway**
cosmos-sdk reverted back the antehandler. 
this pr is to add back antehandler to gaia.
however, the test failed due to ibc-go version

### CODE REVIEW

**Comment by faddat** [comment]
closes #1504

**Comment by faddat** [comment]
PR incoming....

**Comment by faddat** [comment]
This is picking up on red herrings.  Merge https://github.com/cosmos/gaia/pull/1507

**Comment by faddat** [comment]
The actual issue is in the liqudity module, viz:

Take this branch

do like:

```bash
go mod edit -replace github.com/cosmos/ibc-go/v3=github.com/notional-labs/ibc-go/v3@7d35705
go mod tidy -go=1.18
```

you get:

```
 go mod tidy -go=1.18
go: downloading github.com/cosmos/cosmos-sdk v0.46.0-rc1
go: finding module for package github.com/cosmos/cosmos-sdk/x/auth/middleware
github.com/cosmos/gaia/v8/app imports
	github.com/gravity-devs/liquidity/v2/x/liquidity tested by
	github.com/gravity-devs/liquidity/v2/x/liquidity.test imports
	github.com/gravity-devs/liquidity/v2/app imports
	github.com/cosmos/cosmos-sdk/x/auth/middleware: module github.com/cosmos/cosmos-sdk@latest found (v0.45.4), but does not contain package github.com/cosmos/cosmos-sdk/x/auth/middleware
```

Can make PR, but it will fail to tidy for the reasons above.

**Comment by faddat** [comment]
https://github.com/cosmos/gaia/pull/1508


PR is there

**Comment by yaruwangway** [comment]
> #1508
> 
> PR is there

Hi @faddat  this is helpful. thank you!  what is the branch name  of `github.com/notional-labs/ibc-go/v3 7d35705` ? and is this branch ready for use/import?

**Comment by yaruwangway** [comment]
update: waiting for liquidity bumping to sdk0.46-rc1

**Comment by yaruwangway** [comment]
close due to merging into https://github.com/cosmos/gaia/pull/1522

**Pull request closed without merging**
