### PR TITLE
refactor: remove unnecessary in writeFile

### LINKED ISSUE #2834: tests/e2e: writeFile unnecessrily leaks a file yet os.WriteFile already handles its functionality
## Summary of Bug

Noticed in our audits that this code https://github.com/cosmos/gaia/blob/4ab68854cfdbc592ed0cbaea48f4654fb89d2924/tests/e2e/io.go#L37-L44

That code invokes `_, err := os.Create` but doesn't capture the file nor close it. That is all unnecessary becasue `os.WriteFile` handles all that logic https://pkg.go.dev/os#Create

It should be done
```diff
diff --git a/tests/e2e/io.go b/tests/e2e/io.go
index 40b316bec..81160d4aa 100644
--- a/tests/e2e/io.go
+++ b/tests/e2e/io.go
@@ -35,10 +35,5 @@ func copyFile(src, dst string) (int64, error) { //nolint:unparam
 
 // writeFile write a byte slice into a file path
 func writeFile(path string, body []byte) error {
-	_, err := os.Create(path)
-	if err != nil {
-		return err
-	}
-
 	return os.WriteFile(path, body, 0o600)
 }
```

## Version
4ab68854cfdbc592ed0cbaea48f4654fb89d2924

/cc @mpoke @elias-orijtech
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

### PR DESCRIPTION
**Pull request by hoangdv2429**
## Description

Closes: #2834
This PR will remove unnecessary code as described in the issue.

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [x] Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] Added `!` to the type prefix if API, client, or state breaking change (i.e., requires minor or major version bump)
* [x] Targeted the correct branch (see [PR Targeting](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
* [x] Provided a link to the relevant issue or specification
* [x] Followed the guidelines for [building SDK modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules)
* [ ] Included the necessary unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
* [ ] Added a changelog entry in `.changelog` (for details, see [contributing guidelines](../../CONTRIBUTING.md#changelog))
* [ ] Included comments for [documenting Go code](https://blog.golang.org/godoc)
* [ ] Updated the relevant documentation or specification
* [x] Reviewed "Files changed" and left comments if necessary 
* [ ] Confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed `!` in the type prefix if API or client breaking change
* [ ] confirmed all author checklist items have been addressed 
* [ ] reviewed state machine logic
* [ ] reviewed API design and naming
* [ ] reviewed documentation is accurate
* [ ] reviewed tests and test coverage

### CODE REVIEW

**Review by p-offtermatt — APPROVED** [review]
LGTM

**Comment by sainoe** [comment]
It makes the E2E tests fail because `writeFile` doesn't have the required permissions anymore.
```
stdout: , stderr: Error: open /home/nonroot/.gaia/config/xxx.json: permission denied
```

**Comment by hoangdv2429** [comment]
@sainoe I will check on what's the right option to give in instead of `0o600`

**Comment by hoangdv2429** [comment]
@sainoe can you trigger the test again sir ?

**Review by mpoke — APPROVED** [review]
LGTM. Thanks @hoangdv2429.

**Pull request merged**
