### PR TITLE
v1.0.0-rc2 Cherry Picks

### PR DESCRIPTION
**Pull request by alexanderbez**
- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/develop/CONTRIBUTING.md#pr-targeting))

- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote tests
- [ ] Updated relevant documentation (`docs/`)
- [ ] Added a relevant changelog entry: `clog add [section] [stanza] [message]`
- [ ] Reviewed `Files changed` in the github PR explorer

______

For Admin Use:
- Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge PR #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Comment by alexanderbez** [comment]
@fedekunze mind helping me out here on simulation updates?

**Review by fedekunze — APPROVED** [review]
🎉

**Comment by jackzampolin** [comment]
building this and deploying to testnet

**Comment by alexanderbez** [comment]
~~Will cut a final v0.36.0 of the SDK once things look good. Then I will update this to use v0.36.0 instead of v0.36.0-rc2.~~

EDIT: Instead we'll cut an v1.0.0-rc2. Once satisified. We'll create a v1.0.0-rc3 that simply has the SDK version finalized. This way operators can checkout/install a specific tag instead of a branch.

**Pull request merged**
