### PR TITLE
Upgrade module

### PR DESCRIPTION
**Pull request by fedekunze**
Replaces #184

- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/master/CONTRIBUTING.md#pr-targeting))

- [x] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote tests
- [ ] Updated relevant documentation (`docs/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Reviewed `Files changed` in the github PR explorer

______

For Admin Use:
- Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge PR #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Comment by fedekunze** [comment]
I want to block this until we add the upgrade module on the SDK's `simapp`.

**Comment by alexanderbez** [comment]
Why is that @fedekunze?  There is nothing to simulate really. If anything, simulation will short-circuit prematurely if an upgrade proposal passes.

**Review by alexanderbez — APPROVED** [review]
updated & tested. ACK.

**Comment by jackzampolin** [comment]
Huge merge! Very excited to see this live.

**Pull request merged**
