### PR TITLE
Bump SDK version to latest master (532ea1872)

### PR DESCRIPTION
**Pull request by alexanderbez**
- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/develop/CONTRIBUTING.md#pr-targeting))

- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote tests
- [ ] Updated relevant documentation (`docs/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Reviewed `Files changed` in the github PR explorer

______

For Admin Use:
- Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge PR #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Comment by alexanderbez** [comment]
I've bisected the localnet CI failure down to https://github.com/cosmos/cosmos-sdk/pull/5029 and I have no idea why. Any clues here would be helpful @alessio

**Comment by mircea-c** [comment]
@alexanderbez what points to that PR as the cause of the failure?

**Comment by alexanderbez** [comment]
Commit `2c96bbbaa` fails, the one right before, `ab81c798c`, works.

```
* 2c96bbbaa - Add support for github.com/99designs/keyring-backed keybases (#5029) (11 days ago) <Alessio Treglia>
* ab81c798c - Merge PR #5084: Sanitize tools Makefile (12 days ago) <Alexander Bezobchuk>
```

**Review by mircea-c — APPROVED** [review]

**Comment by mircea-c** [comment]
Closes https://github.com/tendermint/iac/issues/295

**Pull request merged**
