### PR TITLE
[docs] remove matrix chat - update explorers and wallets

### PR DESCRIPTION
**Pull request by hxrts**
Gaia description also needs an update, but will save that for later

## Description

Closes: #XXX

- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/develop/CONTRIBUTING.md#pr-targeting))

- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote tests
- [ ] Updated relevant documentation (`docs/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Reviewed `Files changed` in the github PR explorer

### CODE REVIEW

**Review by alexanderbez — APPROVED** [review]

**Comment by tac0turtle** [comment]
could you make this change on main as well. we started a migration but were not able to complete it yet.

**Comment by hxrts** [comment]
> could you make this change on main as well. we started a migration but were not able to complete it yet.

Hmm, looks like main and master docs have diverged significantly and the docs commits will all have to be cherrypicked.

**Comment by tac0turtle** [comment]
> Hmm, looks like main and master docs have diverged significantly and the docs commits will all have to be cherrypicked.

yea this is the part that hasnt been migrated yet. Now that I think about this lets merge and ill migrate in the coming days

**Review by tac0turtle — APPROVED** [review]

**Comment by hxrts** [comment]
btw @marbar3778 the 'found an issue' button on the docs page brings you to the master branch, so if we're shifting to main then we may want to change that link as well.

**Pull request merged**
