### PR TITLE
cosmos/governance -> cosmos/gaia

### PR DESCRIPTION
**Pull request by faddat**
## Description

Moves the governance repository into gaia, ensuring that users get a complete `gaia` when they `git clone https://github.com/cosmos/gaia`

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/main/README.md#merging-a-pr))

### CODE REVIEW

**Comment by dcwalk** [comment]
Hiya! I made a small PR on your branch with some additional cleanup: https://github.com/faddat/gaia/pull/22:
- merging the codeowners file
- removing some of the unneeded config/deploy stuff
- removing the COC and Contributing as they point back to the main gaia ones
- very small fixes to two titles

**Comment by dcwalk** [comment]
To interlink conversations, this merge will closeout issues in `governance`: 
- https://github.com/cosmos/governance/issues/41
- https://github.com/cosmos/governance/issues/11

**Comment by okwme** [comment]
thank you @faddat !
@dcwalk this looks good to go, is there anything else needed before merge?

**Comment by dcwalk** [comment]
We're good to merge @okwme ! I'll follow up in the other repo to complete post-merge steps :rocket:

**Review by okwme — APPROVED** [review]

**Pull request merged**
