### PR TITLE
deps: update several things at once (sdk, cometbft, ibc-go, btcd)

### PR DESCRIPTION
**Pull request by faddat**
- bumps
- ibc-go
- ibc-go v4.4.0

## Description

This PR updates various libraries, and removes a few replace statements.  These changes are intentionally grouped, because they will not work correctly independent of one another:

* cometbft v0.34.28
* cosmos-sdk v0.45.16-ics
* btcd v0.23.0
* ibc-go v4.4.0

Once again, just to be as clear as possible: the dragonberry replace statement has not been needed for a long time.  The latest version of comet will work best with the latest sdk, and same thing for ibc-go.  So these changes have been grouped, and they should be grouped. 

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [x] Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] Added `!` to the type prefix if API or client breaking change
* [x] Targeted the correct branch (see [PR Targeting](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
* [ ] Provided a link to the relevant issue or specification
* [ ] Followed the guidelines for [building SDK modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules)
* [ ] Included the necessary unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
* [ ] Added a changelog entry to `CHANGELOG.md`
* [ ] Included comments for [documenting Go code](https://blog.golang.org/godoc)
* [ ] Updated the relevant documentation or specification
* [x] Reviewed "Files changed" and left comments if necessary 
* [x] Confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed `!` in the type prefix if API or client breaking change
* [ ] confirmed all author checklist items have been addressed 
* [ ] reviewed state machine logic
* [ ] reviewed API design and naming
* [ ] reviewed documentation is accurate
* [ ] reviewed tests and test coverage

### CODE REVIEW

**Review by shaspitz — APPROVED** [review]
Approved, but the version bump of ICS is not not needed, the diff between v1.2.1 and v1.1.1 is just consumer side changes

**Comment by faddat** [comment]
hey @smarshall-spitzbart would you like to keep the update to v1.2.1 or should I change it?

**Comment by shaspitz** [comment]
> hey @smarshall-spitzbart would you like to keep the update to v1.2.1 or should I change it?

You should remove just the update to ICS, thank you

**Comment by shaspitz** [comment]
Superseded by https://github.com/cosmos/gaia/pull/2498, @faddat your commits and credit were maintained in the new PR

**Comment by faddat** [comment]
Just out of curiosity, what's the difference? I'll go have a look 🙂

**Pull request closed without merging**
