### PR TITLE
Gaia v6.0.5

### PR DESCRIPTION
**Pull request by faddat**
## v6.0.5

This pull request:

* removes cosmos/gorocksdb replace statement, in favor of tm-db v0.6.7
* Updates the cosmos-sdk and tendermint to their latest applicable versions

#1449 
______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/main/README.md#merging-a-pr))

### CODE REVIEW

**Comment by okwme** [comment]
thanks for the PR @faddat , can you take a look at the CI errors?

**Comment by faddat** [comment]
hey sorry, I missed these!

**Comment by faddat** [comment]
Sorry I didn't miss anything.  This is related to issues I reported earlier. 

Recommend following the instructions for using golangci-lint:

https://golangci-lint.run/usage/install/#ci-installation

**Comment by okwme** [comment]
thanks for these changes @faddat, even though the release policy doc is still a draft it would satisfy the requirements to merge this as cosmos sdk [v0.44.8](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.44.8) and Tendermint [v0.34.19](https://github.com/tendermint/tendermint/blob/v0.34.19/CHANGELOG.md#v0.34.19) contain security bug fixes.

**Pull request merged**
