### PR TITLE
fix: typos in documentation files

### PR DESCRIPTION
**Pull request by leopardracer**
This pull request contains changes to improve clarity, correctness and structure.

**Description correction:**
Corrected `k yes` to `keys`
Corrected `protcols` to `protocols`
Corrected `plaftorm` to `platform`

Please review the changes and let me know if any additional changes are needed.

### CODE REVIEW

**Comment by leopardracer** [comment]
@mpoke @MSalopek Hi! I’ve just submitted a pull request. Could you please review it when you have a chance? I’d appreciate your feedback and any comments. Thank you!

**Review by MSalopek — APPROVED** [review]

**Review by mpoke — APPROVED** [review]

**Comment by leopardracer** [comment]
@zmanian @jackzampolin Any additional changes before merging?

**Comment by mpoke** [comment]
@leopardracer please resolve the conflicts

**Comment by leopardracer** [comment]
> @leopardracer please resolve the conflicts

what conflicts and how?

**Comment by mpoke** [comment]
> > @leopardracer please resolve the conflicts
> 
> what conflicts and how?

rebase on main

**Pull request closed without merging**
