### PR TITLE
feat: liquidity module

### PR DESCRIPTION
**Pull request by faddat**
## Description

- add liquidity module for future removal
- add the liquidity module to the cosmos hub repo

This PR is aimed at making the process of bringing the liqjuidity module into the cosmos hub repository easier, which in turn will make the eventual removal of the liquidity module easier. 

Reasoning: currently it is difficult to make changes to the liqudity module.  As far as I know, B-Harvest is no longer being paid to work on this.  I think that Gaia should solve her own problems. 

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [x] Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] Added `!` to the type prefix if API or client breaking change
* [x] Targeted the correct branch (see [PR Targeting](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
* [ ] Provided a link to the relevant issue or specification
* [ ] Followed the guidelines for [building SDK modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules)
* [ ] Included the necessary unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
* [ ] Added a changelog entry to `CHANGELOG.md`
* [ ] Included comments for [documenting Go code](https://blog.golang.org/godoc)
* [ ] Updated the relevant documentation or specification
* [ ] Reviewed "Files changed" and left comments if necessary 
* [ ] Confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed `!` in the type prefix if API or client breaking change
* [ ] confirmed all author checklist items have been addressed 
* [ ] reviewed state machine logic
* [ ] reviewed API design and naming
* [ ] reviewed documentation is accurate
* [ ] reviewed tests and test coverage

### CODE REVIEW

**Comment by mpoke** [comment]
@faddat Thank you for your contribution. Please note that there are already two open issues on this topic: this EPIC https://github.com/cosmos/gaia/issues/2084 and this issue https://github.com/cosmos/gaia/issues/2346. Please participate in discussions with the other contributors before opening PRs.

**Comment by faddat** [comment]
@mpoke I take issue with the plan.  I don't think it is realistic, and I think that it amounts to slashing users. 

I think that anyone should open a PR to any cosmos repo that they'd like to, for any reason, and that contributions should not be resented.

Do you have any proof that the path unwinding needed to affect the change described in #2084 and #2346 without harming user funds and harming trust in the hub is possible in the next 6 months, given that counterparty chains would need to assent?

Why are you / informal systems promoting a course of action that will by necessity result in the loss of user funds?

**Comment by mpoke** [comment]
> I take issue with the plan. I don't think it is realistic, and I think that it amounts to slashing users.

@faddat Thank you for your feedback. Please share it on the opened issues (i.e., https://github.com/cosmos/gaia/issues/2084, https://github.com/cosmos/gaia/issues/2346) and participate in the discussions. 

> I think that anyone should open a PR to any cosmos repo that they'd like to, for any reason, and that contributions should not be resented.

We encourage and appreciate all contributions to this repo. To ensure a smooth workflow for all contributors, [a general procedure for contributing has been established](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#workflow). **_Please respect the other contributors and their work._**

**Comment by faddat** [comment]
@mpoke please let me know what I've said or done that's disrespectful.

I mean there was that one time I gave your CEO Bucky double middle fingers while on the Don Cryptonium show, but I very hope he knows I no longer feel that way about him, and that was more than a year ago now, and I imagine I had some choice words and it was likely disrespectful.  But sir, what about this PR is disrespectful?

It is my strong opinion that you're framing this contribution itself as disrespectful, and I respectfully disagree with that stance.

Since you seem inclined to reject this pull request, I'd like evidence that the plans in those issues are viable.

I'm claiming:

1) there is little to no chance that the path unwinding option is viable on any reasonable timeline. 
2) simply removing the liquidty module from the hub is no different from a slashing proposal at this time

....therefore it makes sese to not damage trust, and to keep the module.

I also have a practical problem:

https://github.com/cosmos/gaia/actions/runs/4931156061/jobs/8812901629?pr=2423

any idea what is going on there with the grpc queries?

**Comment by faddat** [comment]
Ok problems resolved.  Did you review the state of that errors package @mpoke

**Comment by jtremback** [comment]
@faddat See my comment [here](https://github.com/cosmos/gaia/issues/2346#issuecomment-1544247440).

As far as I can tell, @dongsam's migration will return all but $1000 of the pool balances to their owner's accounts. Correct me if I'm wrong.

I don't think it's worth bringing a zombie module in the codebase for $1000 instead of just transferring to the community pool and sorting it out from there.

This will be going to governance first in any case.

**Comment by faddat** [comment]
@jtremback much, much better than a stick in the eye sir.

(or a dead module in the codebase)

please expect my yeswithveto.

Since you @jtremback and @mpoke work for the same organization in Cosmos, maybe you can tell me what he found offensive about this pull request?

He's making some pretty bold claims here and I'm confused, officially confused, as a cosmos hub contributor.

**Comment by faddat** [comment]
Another thing I'd like to add @jtremback -- I notice that your comment is from two days ago.

What was @mpoke referring to?  Sorry to keep bringing this up but it is clearly relevant to the code, to him, anyhow.  It seems he feels I had disrespected other contributors and that is worrisome to me.

Marius' comment, as well as this PR, are much more than two days old.  So, maybe @mpoke can please clarify what the issue was?

**Pull request closed without merging**
