### PR TITLE
Faddat/release/v5.0.9

### PR DESCRIPTION
**Pull request by faddat**
## Description
Updates to tendermint 0.34.14

______

For contributor use:

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/main/README.md#merging-a-pr))

### CODE REVIEW

**Comment by yaruwangway** [comment]
Hi @faddat , release v5.0.8 is a backport which is already released, is there any issues, why would you like to bump tendermint version? 😁

**Comment by yaruwangway** [comment]
> Hi @faddat , release v5.0.8 is a backport which is already released, is there any issues, why would you like to bump tendermint version? 😁

Is it becuase of this issue #735 ?

**Comment by faddat** [comment]
Improved relayer performance. 

Also, my apologies:  I'd meant to name this v5.0.9

**Comment by mohammedpatla** [comment]
Bump we need this fix. Any bugs this release has?

**Comment by faddat** [comment]
@yaruwangway it is a relayer performance thing, but I prefer that we focus on #1099 instead.

**Pull request closed without merging**
