### PR TITLE
added mainnet repository to Gaia for consolidation & better ease of use

### PR DESCRIPTION
**Pull request by faddat**
Closes: #XXX

## Description

A common anti-pattern in cosmos is to have netowrk information outside of the blockchain's main repository.  This ensures that a single `git clone` provides everything needed to run gaia successfully.

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/main/README.md#merging-a-pr))

### CODE REVIEW

**Review by alexanderbez — COMMENTED** [review]
ACK, but I would rather have these exist under `networks/` rather than `docs/`.

**Comment by faddat** [comment]
can do :)

**Review by alexanderbez — APPROVED** [review]

**Review by ValarDragon — APPROVED** [review]
Idea LGTM! Have not checked changes in detail

(We recently merged Jacob's PR for this into Osmosis, thanks for improving the node operations across the ecosystem 🙏 )

**Comment by ValarDragon** [comment]
I do recommend using git lfs (and whoever owns cosmos org paying for sufficient git lfs bandwidth) instead of massive files burdening git clones

**Comment by jackzampolin** [comment]
I think we should block this PR on the git ltfs thing if thats going to make cloning more difficult

**Comment by sunnya97** [comment]
+1 on git-lfs

**Pull request closed without merging**
