### PR TITLE
Fix error handling and fix linting

### PR DESCRIPTION
**Pull request by faddat**
This pr:

Fixes linting, we used obsolete linters.
Fixes linting, we had a diff check in place that made PR's to other versions of gaia fail by default because we would run the linters on the 
diffs. 
Fixes error handling in export.go, we did not check errors.

I'll now take those same changes and apply to v6.0.5 and since it won't run linters on diffs we won't have errors.  I honestly figured that the hub maintainers were aware of this.

### CODE REVIEW

**Comment by faddat** [comment]
Oh, and the codecov report?

total red herring

this pr definitely improves gaia.

**Review by yaruwangway — APPROVED** [review]

**Comment by okwme** [comment]
Hi @faddat thank you for the PR.
Can you clarify further, my understanding of the use of diff was so that we don't run linters on code that already had linters running on it.
you're saying that the diff setting is not having this effect and is instead resulting in linters being run on incomplete code and therefore incorrectly failing?
In general I would like to change our CI so that linting is not unnecessarily run since every PR takes so long to pass tests, even when the changes are just markdown files.

**Comment by faddat** [comment]
Yes, if we use that diff thingy for linting, we do not end up linting historical code, and if we continue to use the diff thingy it causes matienance issues on older gaias.  As explained in #1449 -- the diff doodad it'll work if we've just got one release we're maintaining and otherwise it ... it is a straight path to not-good-times.

#1449 

golangci-lint does not add any significant time to the ci runs. 

It is run in parallel with the other linters, and since it is slower than the slow ones, is nbd.

**Comment by faddat** [comment]
codecov is a red herring factory, see #1449

**Comment by faddat** [comment]
Odd thing about response times.


https://github.com/cosmos/gaia/pull/1577

**Comment by faddat** [comment]
this is just getting silly.

I've been elected to validate the hub by my delegators. 

Validators are supposed to check through the code.

I found that we were behind where we should be, linting-wise.  

I solved that. 

What is going on here guys?

Please don't lock this PR, it is the appropriate place for this conversation.

This is a security-enhancing PR from May 26.  It is July 10.

If you do not wish my contributions to hit this repository, **I understand** but I need for the cosmos hub team lead, @okwme  to say that so that I can inform my delegators.

**Review by tac0turtle — APPROVED** [review]
Lgtm. Let's keep the scope of prs small. Can we spin out the action changes to a different pr please

**Comment by faddat** [comment]
sure thing

**Comment by faddat** [comment]
I've removed github actions changes from this PR.

**Comment by okwme** [comment]
thanks for the pr @faddat and thank you for the review @marbar3778 
merging now

**Pull request merged**
