### PR TITLE
chore: gofumpt code formatting for v7

### PR DESCRIPTION
**Pull request by faddat**
This applies gofumpt code formatting to gaia v7.

### CODE REVIEW

**Review by yaruwangway — APPROVED** [review]

**Comment by yaruwangway** [comment]
ha, this is against release branch, not main. can  you please change it to against main ? @faddat  thanks

**Comment by faddat** [comment]
ah, this is supposed to be for v7.

I could do another for main though.

**Comment by faddat** [comment]
@yaruwangway sir, I'd already fumpted main, now you can have your pick between 2 pr's

https://github.com/cosmos/gaia/pull/1512

and 

#1581 


Odd thing about response times.

https://github.com/cosmos/gaia/pull/1577

**Review by tac0turtle — APPROVED** [review]
Lgtm

**Review by okwme — APPROVED** [review]

**Pull request merged**
