### PR TITLE
Add governance and mainnet

### LINKED ISSUE #977: Clean up Gaia repo
## Summary

Gaia is full of stale issues and out of date docs. Let's make it a better place to live.

## Proposal

* close stale issues
* solve real issues
* update all docs
* add governance to this repo
* add mainnet to this repo
* update docs build system
* add some flair

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

### PR DESCRIPTION
**Pull request by faddat**
Closes: #977 

## Description

Makes the gaia repository the source of truth for information about Gaia. 

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/main/README.md#merging-a-pr))

### CODE REVIEW

**Comment by alexanderbez** [comment]
Ughhh, so how is anyone supposed to review this?

**Comment by faddat** [comment]
#977 

-- Please feel free to let me know how to make it easier to review.  

Here are a few thoughts:

1) Since this simply copies in the governance repo, that could be reviewed with sha256sum.  Nothing's changed except for the removal of the .git folder.

2) I can break it into a governance PR and a mainnet repo PR

**Comment by alexanderbez** [comment]
Can we break these down into smaller pieces/PRs? The diff is 200+ files. This is not reviewable :-/

**Comment by dcwalk** [comment]
Like minds! We were talking about merging Governance into Gaia here: https://github.com/cosmos/governance/issues/41

We have a few changes ahead of main in Governance repo where we add in [parameters and a way to query the chain](https://hyphacoop.github.io/governance/params-change/param_index.html): https://github.com/hyphacoop/governance/tree/add-vuepress     that we'd like to upstream into gaia as part of a merge.

If you split off the governance stuff, I am happy to assist by submitting a PR for gov repo that blends changes from both main cosmos governence + hypha's governance repos (from conversation it doesn't seem like commit history needs to be preserved).

Or if you'd like to submit both PRs I can comment on the new gov PR with pointer to relevant files!

**Comment by yaruwangway** [comment]
Hi so basically, we are moving two repos: [cosmos/mainnet](https://github.com/cosmos/mainnet) and [hyphacoop/governance](https://github.com/hyphacoop/governance/tree/add-vuepress) into gaia ? and both of there repos are mainly documents ?

mainnet repo has already reviewed before moving to here. not sure the governance repo ?

we just make sure both repos moved into gaia in the right dir and with right structure,  maybe reading through once more the docs at last?
Do I understand correctly ?

**Comment by alexanderbez** [comment]
Please do the mainnet docs stuff in one PR and any governance stuff in another PR 👍

**Comment by dcwalk** [comment]
@yaruwangway to answer this question

> mainnet repo has already reviewed before moving to here. not sure the governance repo ?

Governance repo docs were reviewed and updated over the last 3 months! After they are merged into Gaia there will likely be some changes and improvements to the doc structure

**Comment by faddat** [comment]
Ok I'll separate these PR's now

**Pull request closed without merging**
